### ISSUE TITLE
Picture display of configure instrument

### ISSUE THREAD

**Issue by morbidslug** [McStasMcXtrace/McWeb#1]
In configure.html put a display of the particular instrument chosen to simulate if there is a .png file with the same basename as the simulation itself.

**Comment by willend** [comment]
Easy to do in mcweb-ng

**Comment by willend** [comment]
Ideas:

INSTRUMENT.instr is uploaded with INSTRUMENT.png (picture) and INSTRUMENT.doc, (contains html or simple ascii input for an optional figure caption)

Inserted optionally below list of instruments, above list of parameters on configure page. (Consider javascript or other way of "hiding" this info via a link)

**Comment by willend** [comment]
Latest push to master includes this feature
