### ISSUE TITLE
moodle quizz bug in intro-ns

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McWeb#101]
The quizz "Choice: Semi-classical or quantum mechanical description of nuclear scattering" in the module "Basics of neutron scattering" gives an error message when the user attempts to start the quizz.

![moodle_quizz_bug](https://cloud.githubusercontent.com/assets/11196009/25897548/9bf4d6ba-3588-11e7-9dbe-3c455cf87293.png)

**Comment by lindaudby** [comment]
Resolved. Go to edit quiz, Set maximum grade=0.0
![screenshot from 2017-05-10 14-50-40](https://cloud.githubusercontent.com/assets/15801156/25899457/3f5a2a74-3590-11e7-9013-5ddc7c0798ac.png)

**Comment by climbcat** [comment]
Alright, now we can close the issue. We will still be able to refer to it later on.

**Comment by willend** [comment]
OK, resolved. Closing
