### ISSUE TITLE
Tudelft NXP: missing Lefman pencast

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McWeb#102]
A pencast is missing or bugged in the nxp tudelft instance (and possibly elsewhere). 

"Hej Jakob,
Med den sidste module virker for en fra min studenter de tre sidste problemer ikke."

![nxp_missing_pencast](https://cloud.githubusercontent.com/assets/11196009/25898203/605285dc-358b-11e7-9b5b-d771ed8d4c5d.png)

**Comment by lindaudby** [comment]
This is very unfortunately due to discontinuation of the pencast show software :/ We will probably not be able to recover the cast as a videofile.
Will try to make e new one using an ipad instead and hide the action in the course meanwhile.

**Comment by climbcat** [comment]
Could we simply link to a youtube? If it is ok to put the material into the public that is.

**Comment by lindaudby** [comment]
Problem is we have no access to a youtube playable file.The cast was recorded via a special pen that can only send the cast to this livescribe online platform which has now been discontinued. Stupid system, we should in retrospect have used another recording system. Will probably use ipad from now on.

**Comment by willend** [comment]
Too bad. Marked as wontfix, I guess there is not much we can do at this point. Closing
