### ISSUE TITLE
Make a way to get the instrument menu in livesim

### ISSUE THREAD

**Issue by PJRay** [McStasMcXtrace/McWeb#108]
Right now, you have to change "/instrument/..." to "/instrument-menu/..." in the livesim in order to get the menu for instrument groups (and instruments in those groups) in the top of the page.

It would be great if we could have a button on the top of the page that simply opens the menu - maybe a simple link to the right of the e-neutrons and McStas logos. Or a button next to the Logout button.

**Comment by climbcat** [comment]
Hi. Question: Linda has previously requested that the menu be kept away from students, in order to not distract them from the instrument at hand. However, a small manu may not distract them much. Or do you want to keep this menu hidden for non-superusers?

**Comment by lindaudby** [comment]
Let's try with a menu button which is visible to all. The students of a particular course is referred to a particular instrument in that course through an url in the quiz. Thus they should not be distracted by a small link on the top of the instrument page leading to instrument-menu.

**Comment by climbcat** [comment]
A menu open/close link has been implemented, this will be added to the server shortly.

**Comment by lindaudby** [comment]
Do I need to do something specific in my browser to see the implementation?

**Comment by willend** [comment]
Hi Linda,

I think it was not yet pushed to the "production" server - see below for screenshots from a machine we are currently setting up at DTU (not on the web yet...)

![safariscreensnapz087](https://user-images.githubusercontent.com/8593355/26967798-dfd3fe9a-4cff-11e7-858a-bf16245e91a7.png)
![safariscreensnapz088](https://user-images.githubusercontent.com/8593355/26967800-e2638df6-4cff-11e7-84e8-ffed7e5a6b18.png)

**Comment by willend** [comment]
Is now online at the "production site" e-neutrons.org

**Comment by willend** [comment]
Closing as this is now implemented according to the discussed
