### ISSUE TITLE
Registerred users counter on e-neutrons frontpage

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#109]
Would be great if we had a counter on the number of registerred users in the database which could then be show e.g. on the e.neutrons frontpage.

**Comment by climbcat** [comment]
A counter has been implemented, which will be tested on the server tomorrow.

**Comment by lindaudby** [comment]
Do I need to do something specific to my browser in order to see the counter?

**Comment by willend** [comment]
Again, not yet pushed to the production server, will become available through a URL like 
http://sim.e-neutrons.org/howmany 

- which will then be exposed somewhere on the wordpress similar to the "logged in" status stuff at the top

**Comment by willend** [comment]
Is now visible in the page footer at http://www.e-neutrons.org

(Shows #signups which is perhaps not 1:1 the #registered users - @climbcat let's discuss this tuesday)

**Comment by climbcat** [comment]
Yes, we could subtract a fixed number, defined in settings for example?
