### ISSUE TITLE
Prototype sign-up form at e-neutrons.org

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#11]
Features:
- Give email and desired username
- Defines a line in a CSV file for application by https://github.com/McStasMcXtrace/McWeb/blob/master/ldifs/ldap_addusers.py
- (We should adhere to a moodle-compatible CVS format with course1, course2, ... etc)

**Comment by willend** [comment]
1) HTML-form makes GET call to django app in a target=_blank
2) urls.py updated to take information from the form, e.g.
  - email
  - name
  - wanted courses etc
3) django adds this information to csv file, 
4) Cron: sent once pr day to admin for further processing, clearing out the old csv.

**Comment by willend** [comment]
Did we decide to make this a django / mcsimrunner_ng page?

**Comment by climbcat** [comment]
a prototype sign-up app has now been created. It lives in the simrunner, url = /signup/. It writes lines to a csv file of the type '%s;%s;%s;%s;%s\n' % (firstname, lastname, username, email, password) and header "firstname;lastname;username;email;password\n". Passwords are not captured or generated in this app.

**Comment by lindaudby** [comment]
Great that you created a sign-up app! I think Moodle might need a 
specific order in the csv
username, firstname, lastname,email, password

But I'm not sure since I never got upload from csv working ...

How are passwords captures or generated then if not in the app?

On 12/15/2015 01:30 PM, Jakob Garde wrote:
>
> a prototype sign-up app has now been created. It lives in the 
> simrunner, url = /signup/. It writes lines to a csv file of the type 
> '%s;%s;%s;%s;%s\n' % (firstname, lastname, username, email, password) 
> and header "firstname;lastname;username;email;password\n". Passwords 
> are not captured or generated in this app.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/McStasMcXtrace/McWeb/issues/11#issuecomment-164749941>.
>


-- 
----------~oOo~----------
Dr. Linda Udby
Associate Professor
X-ray and Neutron Science
Niels Bohr Institute
University of Copenhagen
tel: +45 23 83 98 77
----------~oOo~----------

**Comment by climbcat** [comment]
Hi, passwords are generated. When a user is created after the admin has checked that the new_users.csv file ok, an email is sent to the user with the password. They can change their passwords through moodle afterwards. They may also not be able to get the username they want, if it was already taken. The admin then has to pick anbother username for them, and then add them to the system. We will not check that emails are unique.

**Comment by climbcat** [comment]
This is progressing, current issues: 

- generate a random password for the users and put it into the csv
- send an email to newly added users with instructions and password (?)
- finally, delete csv file newusers_some_date

(OR should passwords be generated and sent to users by ldap_addusers?)

**Comment by willend** [comment]
The mkpasswd (unix) tool is quite nice for randomised passwords - I suggest that the CSV file lines are created with this password for convenience? 

The mail for the user should only be sent at account creation, e.g. in ldap_addusers I think.

**Comment by willend** [comment]
Just gave the page a spin in my VM - looks good, but we need a 'list of courses' that the user can 'ask' to be enrolled in. course1;course2; etc in the csv - understood by moodle. 

For now a hardcoded list will do I guess - @lindaudby  what are the 'Moodle short names' of the courses that are relevant at this point?

**Comment by climbcat** [comment]
alright, cool - yes, it would have to be hardcoded. The idea is to host a sign-up form at e-neutrons.org (or anywhere else) as pure html. The drop-down would have to be updated by hand also.

**Comment by willend** [comment]
- But I guess it could in theory be a python-based 'list' in settings.py?

**Comment by climbcat** [comment]
question: are the courses booleans, one column for each course?

answer: in theory they could be, but then we would have to implement another page and server the signup form via django. This means problems with flexibility and styling, if the form is to be embedded in e.g. the e-neutrons site

**Comment by climbcat** [comment]
Ok I'll presume checkboxes / booleans, and implement the whole thing it as list tomorrow, then we can always generate a html page from a django template, and just copy-paste that to be hosted. Sounds like a plan it wont take long.

**Comment by climbcat** [comment]
Dynamic course signup stuff: 

- update mcweb.settings.COURSES
- run "python manage.py signupform" to get a form that can be embedded in any html page
- OR use the url /signup/ to test

The signups are written to the file new_signups.csv, with a column for each entry in the COURSES list. The values are python True/False booleans. A random password is generated for each user, using makepasswd (which is now a requirement).

**Comment by lindaudby** [comment]
The relevant courses to enroll students in are currently

intro-ns-selfstudy
intro-ns
musr
lib

Everyone needs auto-enrollment in lib.


On 12/15/2015 08:52 PM, Peter Willendrup wrote:
>
> Just gave the page a spin in my VM - looks good, but we need a 'list 
> of courses' that the user can 'ask' to be enrolled in. 
> course1;course2; etc in the csv - understood by moodle.
>
> For now a hardcoded list will do I guess - @lindaudby 
> <https://github.com/lindaudby> what are the 'Moodle short names' of 
> the courses that are relevant at this point?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/McStasMcXtrace/McWeb/issues/11#issuecomment-164875935>.
>


-- 
----------~oOo~----------
Dr. Linda Udby
Associate Professor
X-ray and Neutron Science
Niels Bohr Institute
University of Copenhagen
tel: +45 23 83 98 77
----------~oOo~----------

**Comment by climbcat** [comment]
this is done, down to robustness details

**Comment by willend** [comment]
DONE
