### ISSUE TITLE
Ændre e-mail væk fra hougaard@nbi.ku.dk på forsiden, og måske klarere kontakt-information?

### ISSUE THREAD

**Issue by PJRay** [McStasMcXtrace/McWeb#114]
På For Teachers siden (https://www.e-neutrons.org/?page_id=69) står der stadig at man skal kontakte hougaard@nbi.ku.dk - det skal nok lige fjernes, og evt. rettes til Linda?

**Comment by lindaudby** [comment]
jep, godt spottet Pia,

Jakob kan du ændre kontakt email til udby@nbi.dk?

**Comment by willend** [comment]
Jakob er på ferie de næste par uger, men jeg har ændret passende.

(Jeg synes vi skal overveje at ændre alle hardkodede "person" email adresser til etellerandet@e-neutrons.org)

**Comment by lindaudby** [comment]
Tak for det.
Enig, det ville give mening at lave feks en teacher@e-neutrons.org (der kan forwardes til mig) og en tech@e-neutrons.org (kan evt kunne forwardes til Peter eller Jakob).

**Comment by willend** [comment]
Eller bare en fælles "postkasse"/mailingliste. Der er ofte aspekter af begge dele  i de ting folk spørger om...

**Comment by lindaudby** [comment]
fint for mig

**Comment by willend** [comment]
Så er modtager rettet til admin@e-neutrons.org - som går til den fælles admin-mailingliste, der pt. inkluderer Linda, Jakob, Pia og undertegnede.

**Comment by willend** [comment]
Alternativt kunne en passende kanal på slack måske være helt åben? Jeg aner blot ikke hvordan man sætter den slags op...

**Comment by lindaudby** [comment]
Hmm det er egentlig også en god idé. Det fungerer sådan a man kan skrive et link som folk skal klikke på hvorved de inviterer sig selv til kanalen. Invittaion skal godkendes af den der har oprettet den og så er de med.
Vi kan sagten bruge vores Slack team  og oprette en extra åben kanal dér men hvis dte kun er den som de nye brugere skal se så skal alle de andre kanaler gøres private.

Jeg er græsk-katolsk, det med mailen er oså fint, men selvfølgelig smart hvis vi som team kan diskutere med brugeren direkte.

**Comment by lindaudby** [comment]
Nå, testede lige. Man skal desværre enten være fra en liste af approved email adresser eller have en invitation fra teamet, man kan ikke signe up og så blive approved derefter :/
Så måske havner vi alligevel på den oldschool emailliste løsning...

**Comment by willend** [comment]
OK. Lad os køre lidt med det som det er så.

**Comment by lindaudby** [comment]
Hvad er admin pass til mailinglisten? Skal bruges for at folk udefra kan poste, som nu hvor Peter BAker gerne vil poste et eller andet...

**Comment by lindaudby** [comment]
OK fandt pass, og det var bare en auto-svars mail fra PEter B

**Comment by climbcat** [comment]
Hej Linda

Ja, jeg har set det, og der ser ikke vigtigt ud, et autosvar der er blevet sendt videre sikkert ved en fejl, som du siger.

VH
Jakob
________________________________________

**Comment by willend** [comment]
Closing, believe current situation is acceptable
