### ISSUE TITLE
re-shape intro-ns

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#115]
Det ville være mere oplagt for intro-ns kurset hvis det kun indeholder overordnet introduktion til topics, og at de to sidste topics bliver overført til et specialised-ns kursus

**Indhold af intro-ns**

- Basics of neutron scattering
- Neutron sources and instrumentation
- Introduction to Small Angle Neutron Scattering
- Introduction to neutron reflectivity
- Introduction to diffraction from crystalline materials
- Imaging
- Inelastic scattering from lattice vibrations
- Magnetic neutron scattering
- Inelastic magnetic neutron scattering

**Indhold af specialised-ns**
Biological applications of Small Angle Neutron Scattering
Basic Crystallography

De som afhodler kurser (feks KU) kan så bygge dem sammen i eget e-kursus.
Jeg foreslår dette bliver gjort i forbindelse med migrering til ny Moodle.

**Comment by willend** [comment]
I belive you did this @lindaudby ? DONE
