### ISSUE TITLE
broken links in Muon Data Analysis

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McWeb#116]
Submitted by prashantha@qmul.ac.uk:

"Please check
Some lessons in the module Muon Data Analysis does not open (weblink does not work, it shows only a blank page). 
Thank you"

**Comment by lindaudby** [comment]
Who is assigned to this task? I think we need more details from prashanta which specific weblinks to fix

**Comment by willend** [comment]
I believe we can close this ticket as the user got moodle admin rights in the meantime?
