### ISSUE TITLE
Signup tool updates

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#117]
Further input data on "self-enrollment form":
* Institution - maps on to Moodle field
* Country - maps on to Moodle field
* Description - maps on to Moodle field
(Plus email to existing "customers" to fill in these via moodle.... - Or a simple, new form.)

Overview "admin" page - and "menu" on the left on any admin subpage

Allow to edit and remove a given user, bulk remove

Save "deleted" signups (filter userlist_au by those in  / out of the LDAP database)

**Comment by climbcat** [comment]
Also this, from another issue:

**Comment by climbcat** [comment]
Allow users to update their data / input Institution & Country.

**Comment by climbcat** [comment]
Always create a django user or superuser @ add

**Comment by climbcat** [comment]
Check existing usernames signup time.

**Comment by climbcat** [comment]
add a few more ldap_ commands to manage.py - e.g. ldap_chpassword.

**Comment by willend** [comment]
The various mails sent to the user should also automatically indicate the right URL's for a given system, currently hardcoded to be related to e-neutrons.org. 

Example (sent from elearn-1 system)
<pre>

Dear Peter Willendrup

You have been added to the http://e-neutrons.org e-Learning system.

username: peterw
password: (removed)

To change your password, please visit http://www.e-neutrons.org/ssp/

Best,

The e-neutrons.org admin team
</pre>

**Comment by climbcat** [comment]
1) Institution type
Educational
Research Facility
Other

2) Country

3) Research Interest

**Comment by willend** [comment]
https://github.com/McStasMcXtrace/McWeb/issues/155 is related

**Comment by climbcat** [comment]
This has been implemented in the self-signup module (not yet deployed to stable).

**Comment by climbcat** [comment]
This has been implemented.

**Comment by willend** [comment]
Deployed
