### ISSUE TITLE
course short name

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#119]
It would be nice if the date stamp when course was generated is not part of the short course name. It looks messy and difficult to read for the student.

**Comment by willend** [comment]
The date is there to ensure uniqueness of the short-name (which for us serves as "the" identifier to distinguish "versions" of the same course).

Please suggest how uniqueness can otherwise be achieved.

**Comment by lindaudby** [comment]
Ok, I understand. Though uniqueness was only needed for teh *.mbz snaps. Right now no other ideas for uniqueness so keep as is.
