### ISSUE TITLE
Signup: (implemented in Simrunner) Captcha + checking for sign-up form 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#12]
Should apply captcha to avoid robots.
Check string contents /replace/ non-ascii chars etc

**Comment by morbidslug** [comment]
This seems straight forward but we need a google account and a list of websites that will host the noCAPTCHA reCAPTCHA app from google:

http://webdesign.tutsplus.com/tutorials/how-to-integrate-no-captcha-recaptcha-in-your-website--cms-23024

**Comment by jaga-mcstas** [comment]
Let's get an account then :-) The hosted site will be e-neutrons.org

**Comment by willend** [comment]
Can be done, low priority, future

**Comment by willend** [comment]
Related to https://github.com/McStasMcXtrace/McWeb/issues/46.

**Comment by willend** [comment]
Recaptcha endabled via Peter's google account - DONE
