### ISSUE TITLE
Elaern1: missing email notification upon account approval

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#120]
I have bulk-uploaded some accounts to elaern1, one of them a test account to my own email adress. I did not however receive an email with username and password info.

**Comment by willend** [comment]
This is true - system currently has no mail transport to the "outside world", hope to fix this tomorrow

**Comment by lindaudby** [comment]
Ok,thanks.
If I remember correctly there is no way to erase users now?
Which means I have to send individual mails to the users I have created now which includes their username and password?

**Comment by willend** [comment]
If you enrolled less than ~10 people I suggest you do exactly that. 

There is a slightly messy way of deleting accounts, but a very "lowlevel" one...

**Comment by lindaudby** [comment]
ok, I've sent out individual mails
