### ISSUE TITLE
include url-clipping tool into moodle course restore

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McWeb#123]

**Comment by willend** [comment]
Code is this one:

https://github.com/McStasMcXtrace/McWeb/blob/master/scripts/moodle_strip_mbz_URLS

- use in /srv/mcweb/moodle-course-templates:

/srv/mcweb/McWeb/scripts/moodle_strip_mbz_URLS myfile_archive.mbz http://e-neutrons.org/ replace

**Comment by willend** [comment]
- Perhaps simply include at the start of any "restore job" before moosh command(s)?

**Comment by willend** [comment]
Leave as is, tool has side effects, see https://github.com/McStasMcXtrace/McWeb/issues/136
