### ISSUE TITLE
Resurrect support for matplotlib mcplot and mcdisplay

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#128]
Reasoning:
* Allows (headless) generation of hardcopy output
* Can output html, we should see if that can be served via e.g. nginx

Should be implemented using new, centralised loader from mccodelib

**Comment by willend** [comment]
(I guess this is partly a McCode ticket - but is certainly relevant here)

**Comment by climbcat** [comment]
support for mcplot-matplotlib has been resurrected/ported

**Comment by climbcat** [comment]
(Missing: Updating the build scripts for the various distributions.)

**Comment by willend** [comment]
@udby one of the side-effects of having matplotlib available is that we have now found a prototype way of making simulation graphics "interactive". Have a look here:

https://sim.e-neutrons.org/static/doublesynts.html

(Note that it can take substantial time to generate especially the matrix plots - on my mac a 40x50 bin image takes ~1.6 secs and a 201x201 takes 11.8 secs...!)

We were wondering if you think this looks interesting - don't consider details like font sizes etc., please evaluate the "pure" functionality of the 1D and 2D McStas "plots in a browser"

**Comment by willend** [comment]
@lindaudby one of the side-effects of having Matplotlib available is that we have now found a **prototype** way of letting "McStas data on the web" become semi-interactive, see

https://sim.e-neutrons.org/static/doublesynts.html

What do you think? Would this be interesting? (Please consider the "pure" functionality, not font sizes etc. )

(Please be aware that generating these take substantial server time, ~1.6 secs for a 40x50 bin image ~11.8 secs for a 200x200 image on my quad-core Mac)

**Comment by lindaudby** [comment]
I had a look. If I understand the extra features correctly it only involves zooming in on the plots?

**Comment by willend** [comment]
Closing, we will create a McStas/McCode issue for this instead
