### ISSUE TITLE
simrunner neutron rays input format

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#130]
currently the input format for neutron rays "1e6" gives an error in simrunner.
Since it is frequently used in local McStas runs it would be nice to have as an option in simrunner too.

**Comment by willend** [comment]
Agreed

**Comment by willend** [comment]
I would suggest we avoid further changes to the simrunner while your current course is running - "if it works, don't fix it"... 

(I think this is nice to have rather than need to have at this point, the simulator is functional)

**Comment by willend** [comment]
Couldn't help it, found a quick fix... ;-) int(float(1e6)) == 1000000

**Comment by lindaudby** [comment]
Great, thanks:)
