### ISSUE TITLE
"list index out of range" error on self-signups" @ e-neutrons.org 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#137]
<img width="1552" alt="safariscreensnapz025" src="https://user-images.githubusercontent.com/8593355/30126448-42590f2e-933c-11e7-9eb0-364be4d4322b.png">

**Comment by willend** [comment]
Bulk upload works as intended, bug only affects the self-signups

**Comment by willend** [comment]
... And self-signups works OK @ elearn1??

**Comment by climbcat** [comment]
"Priority 1000" yes, definitely :-)

**Comment by willend** [comment]
Fixed on both master and MCWEB_STABLE_2.0
