### ISSUE TITLE
mathjax at e-neutrons

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#139]
It looks like we need to put a link to mathjax in e-neutrons (right now math looks ugly). See screendump of elearn1 vs e-neutrons setup
![screenshot from 2017-09-06 21-56-12](https://user-images.githubusercontent.com/15801156/30131864-a16d93e2-934e-11e7-9dcd-9b6b515c381a.png)

**Comment by willend** [comment]
You are more than welcome to just do that edit yourself - copy-paste across - you are anyway much more on top of Moodle than the rest of us :-)

**Comment by lindaudby** [comment]
Ok, didn't know whether it was the same link or not. Copy pasted and it seems to work :)
