### ISSUE TITLE
/sim/instrument/[instrumentname] always redirects to https://sim.e-neutrons.org/instrument/intro-ns/SANSsimple

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#148]
The link to a specific instrument at e-neutrons only works if input as https://sim.e-neutrons.org/instrument/

not if input as /sim/instrument/ in which case it always defaults to the SANSsimple instrumnt

**Comment by willend** [comment]
I belive this is now corrected via a couple of rewrite rules:

From wiki or moodle /sim/some/instrument expands to
www.e-neutrons.org/sim/some/instrument/ (or e-neutrons.org/sim/some/instrument/)
-> redirects to sim.e-neutrons.org/sim/some/instrument
-> redirects to sim.e-neutrons.org/some/instrument

Have a look to see if it isn't better now?

**Comment by lindaudby** [comment]
Yes, it works now, thanks :)
