### ISSUE TITLE
sim.e-neutrons.org "showing" different plots for same link in different browsers

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#149]
In firefox it looks like there are some extra dataplots which cannot be rendered 
![screenshot from 2017-09-07 21-35-29](https://user-images.githubusercontent.com/15801156/30181881-19ad9200-9415-11e7-82a4-bd3b2d5a171b.png)

whereas in Crome the "empty plots" are not shown
![screenshot from 2017-09-07 21-35-18](https://user-images.githubusercontent.com/15801156/30181856-04b1edec-9415-11e7-8a5e-6cb0f2a2181d.png)

Funky!

**Comment by willend** [comment]
Hi, nothing to do with Firefox. 

The instrument has 3 "PSD" monitors at the end, two of which have an 1x1 binning (which becomes a 0-dimensional rather than 2-dimensional dataset).

I discussed this with Mads the other day - solutions are to either make the same binning as the first PSD or leave the two latter (single vs. multple scattering) out

**Comment by lindaudby** [comment]
OK that they are left out in this case (at least for now). I just wondered why the empty frames are showing in firefox but not in chrome

**Comment by willend** [comment]
Ah ok, that difference I think is only down to the "taste" of web-browser developers (you could say that a webpage with a missing image looks less "broken" in chrome ;-) )

Anyway, we will likely not allow visualisation of 1x1 monitors as they have ONE pixel to show - that I guess would always be of the "central" color of the colormap ;-)

**Comment by lindaudby** [comment]
OK, thanks now I understand what is going on.

**Comment by willend** [comment]
Just as a test, I have now added binning 20x20 like on the first PSD, added via editing the instr in my mounted dav filesystem... https://sim.e-neutrons.org/static/compile_status.html can be used to monitor compilation.

**Comment by willend** [comment]
Works fine the moment monitors are > 1x1, see

http://sim.e-neutrons.org/static/data/mcstas_Ni_TAS_20170908_085714/browse.html
