### ISSUE TITLE
Single-sign-on form for Moodle, McWeb, Mediawiki

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#15]
Likely based on javascript, see first attempt here: https://github.com/McStasMcXtrace/McWeb/blob/master/singlesignon/index.html

**Comment by morbidslug** [comment]
Made an attempt at csrf verification and made the page look liek the other pages. Code duplication occurred. Fix when this works.

**Comment by jaga-mcstas** [comment]
https://docs.djangoproject.com/en/dev/howto/auth-remote-user/

**Comment by willend** [comment]
I have a - perhaps - productive idea for this: 

Put the javascript we currently have in the singlesignon/ folder into the django login template - with Moodle and Mediawiki inside (hidden?) iFrames. We would still need to do something on the Mediawiki side though...

Lets chat about this friday?

**Comment by willend** [comment]
Also look at these:
* https://moodle.org/mod/forum/discuss.php?d=60632
* https://www.mediawiki.org/wiki/Extension:MoodleSSO
* https://moodle.org/plugins/view/auth_mwsso
* https://www.mediawiki.org/wiki/Moodle
* https://www.mediawiki.org/wiki/Moodle/MediaWiki-Moodle_extension

**Comment by jaga-mcstas** [comment]
We need to create a cookie with the sessionid (and possibly the token). This should be managable using js. I think we can find some tips here: http://stackoverflow.com/questions/14573223/set-cookie-and-get-cookie-with-javascript

**Comment by jaga-mcstas** [comment]
- There is no user-specific content in the presentation site, e-neutrons.org. Deep linking in moodle works even if not logged in, and mediawiki is the same (server down, cannot test). Cookies preserve sign-in credentials between browser sessions for these two.
- However, Django will reroute to the login screen if not logged in, and does not auto-create a new session using a cookie between browser sessions.

Therefore, users will have to log on to django (slash/ the single-sign-on) every at every browser-session.

We should add a session-preserving cookie to the django app, which will allow the deep linking to display specific instrument groups through the url. This will be more reliable than the current single-signon from e-neutrons.org, which users may omit. 

We could do this in the future.

**Comment by willend** [comment]
Checkmark for django + moodle, marking as done for now. (mediawiki may come in the future)
