### ISSUE TITLE
bulk enroll email notification to user

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#151]
It would be very nice if upon "add_enroll_somecourse" the user was sent an email with contents
"Dear [firstname]
You have been enrolled in the e-learning course ["somecourse"] on e-neutrons, please follow this link [link to "somecourse"] to see contents. You have previously received an email with your login info for e-neutrons. In case you have forgotten or need to reset your password please follow this link [link to passsword changer ].
Best regards
your e-neutrons team"

At the moment this has to be done manually for each bulk-enrolled participant.

**Comment by willend** [comment]
Done with https://github.com/McStasMcXtrace/McWeb/commit/40f7f3d066c65a2568031674a5f76e1677a0a8c7
