### ISSUE TITLE
simrunner should allow to use gravity

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#153]
We ought to have a gravity "on/off switch" within the "runtime configuration":

<img width="1014" alt="safariscreensnapz030" src="https://user-images.githubusercontent.com/8593355/30343338-80328dfa-97fd-11e7-9bf0-38c7914d0a44.png">

- a simple boolean flag, that would add a -g to the mcrun call.

**Comment by willend** [comment]
Of course only relevant with neutrons, which couples this issue to https://github.com/McStasMcXtrace/McWeb/issues/154

**Comment by willend** [comment]
3 parts:
* Flag on instrument database item to signify if this is a "McXtrace instrument" (check at collect_instr)
* Show checkbox for gravity in the "non-McXtrace" case
* Put -g on mcrun commandline

**Comment by willend** [comment]
semi-functional code for the mcstas/mcxtrace check was available in https://github.com/McStasMcXtrace/McWeb/commit/4789e9cc343dd0191b7c7eabe9ce198e2e706d73

**Comment by climbcat** [comment]
Gravity has now been enabled as an option, requiring a db change to Simrun objects and thus a migrate. Cherry-picked to stable. Automatic updates from should deplot this on monday.

**Comment by climbcat** [comment]
The mcxtrace check has also been enabled in collect_instr, and the code will be deployed on the same conditions.

**Comment by climbcat** [comment]
The gravity field is visible for mcstas instruments only.

**Comment by willend** [comment]
DONE
