### ISSUE TITLE
allow new signup parameters in bulk enroll format

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#155]
The new parameters which will be implemented in self signup such as city/town country should also be able to upload as CSV.

**Comment by willend** [comment]
connected to https://github.com/McStasMcXtrace/McWeb/issues/117

**Comment by climbcat** [comment]
This has now been implemented (not yet in STABLE). Only the cases with four or seven columns are handled, and an exception is thrown othewise.

**Comment by willend** [comment]
Deployed
