### ISSUE TITLE
counter on frontpage "online users"

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#156]
Is it possible to have a counter on the e-neutrons frontpage next to the number of users which specifies the current number of users which are logged in ?

**Comment by willend** [comment]
Hmm, not easy I think. I guess this is mostly for your own information @lindaudby ? Or is it more a "performance indicator"?

Moodle seems to have a way to show who is "currently" online - see https://moodle.org/mod/forum/discuss.php?d=102191 (something about Blocks Drop Down and select “Online Users” )

Alternatively we may try to use moosh for it, 
<pre>
report-concurrency
Get information about concurrent users online.

Use: -f and -t with date in either YYYYMMDD or YYYY-MM-DD date. Add -p te specify period.

Example 1: Get concurrent users between 20-01-2014 and 27-01-2014 with 30 minut periods.

moosh report-concurrency -f 20140120 -t 20140127 -p 30
</pre>
- but I am not sure how well that would work...

**Comment by willend** [comment]
-  moosh report-concurrency -f 20170901 -t 20170912 -p 30 gives nothing on e-neutrons, so I would vote for the simpler "pure moodle" solution

**Comment by lindaudby** [comment]
OK thanks. The reason for wanting it in the frontpage is for the users to get a feel that someone else is also there when they perhaps are visiting for the first time. The "community" feel. But if there is no simple solution, just leave it as is.

**Comment by willend** [comment]
Closing as we agreed to leave as is
