### ISSUE TITLE
In  WIKI: link to Moodle course page is always to intro-ns

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#157]
In the wiki https://www.e-neutrons.org/wiki/index.php?title=Main_Page
left menu there is a link to Moodle course page. This points to the course intro-ns which is confusing to students enrolled in another course. 
Is it possible carry course id in in WIKI user sign-in?

**Comment by willend** [comment]
I suggest to simply let the link instead point to /moodle/my - that way the user is referred to any course(s) (s)he is subscribed to.

**Comment by willend** [comment]
(... and no code would have to be written ;-) )

**Comment by lindaudby** [comment]
Yes, good suggestion! Can you please implement it? (I'm not quite sure how to change the menus in the WIKI)

**Comment by willend** [comment]
OK, can do that. For reference, this stuff is edited as Admin on the page https://www.e-neutrons.org/wiki/index.php?title=MediaWiki:Sidebar

**Comment by lindaudby** [comment]
Thanks!:)
