### ISSUE TITLE
course backup fails

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#158]
I wanted to create a backup of the tartu course
![screenshot from 2017-09-14 13-39-41](https://user-images.githubusercontent.com/15801156/30428030-5fcfc248-9952-11e7-91ad-d59a81b4d3f3.png)
but then I got this error
![screenshot from 2017-09-14 13-39-19](https://user-images.githubusercontent.com/15801156/30428037-69bd5d10-9952-11e7-98bb-d7ce409dd239.png)

**Comment by climbcat** [comment]
Tak for bug report. Vi tager en hel backup af sitet hver mandag morgen - templates er ikke tænkt som backups, men til at rulle "friske" udgaver af et kursus ud.

(Fra Peter: Du må gerne skrive prioriterer på diverse tasks, ellers ved vi ikke hvad der er vigtigst.)

**Comment by lindaudby** [comment]
OK, det var fordi jeg ville være sikker på at gemme nogle edit jeg havde lavet i quizzer hvis nu sitet skulle gå ned inden mandag. Feks skal jeg lige til at uploade et nyt instrument og selvom jeg mener at have gennemtjekket for mærkelige akrakterer vil jeg helelre være sikker på at arbejdet med moodle er gemt forinden.

Hvordan sætter jeg prioriteter på issues? Kan ikek lige umiddelbart se "knappen"

**Comment by climbcat** [comment]
Prioriteter er vores brug af "labels" som du finder til højre (under Assignees). Hele sitet går ikke i stykke pga. et enkelt instrument - det værste der kan ske er, at det ikke dukker op i interfacet.

**Comment by willend** [comment]
Brug labels som på screenshotet nedenfor.

Regler: 

1) Der kan kun være et enkelt task med Priority 1000, et med 900 og et med 800, herefter kan de principielt være sideordnede. 

2) Når et af dem med høj prioritet "lukkes" må du gerne omprioritere / opdatere

![safariscreensnapz027](https://user-images.githubusercontent.com/8593355/30428768-229f3c34-9955-11e7-89a9-442a390fb8f3.png)

**Comment by lindaudby** [comment]
Jeg tror ikke at labels er aktiverede for min konto ...

**Comment by willend** [comment]
Hmm, underligt. Men jeg har nu opgraderet din adgang fra 'Member' til 'Owner', hjælper det? (Evt. skal du logge ud/ind på GitHub)

**Comment by lindaudby** [comment]
Ja det hjalp - nu er der tandhjul ved Labels :)

**Comment by lindaudby** [comment]
@jaga  ... nu prøver jeg så at uploade instrumentet og kryser fingre for at databasen ikke går itu :)

**Comment by willend** [comment]
De ting tror jeg nu ikke har noget med hinanden at gøre - det ene er en moodle ting og det andet er en websimulator-ting...

(Og hvis du kigger nøje efter i dit eget screenshot kan du se referencer til den famøse qtype_algebra...)

**Comment by lindaudby** [comment]
Nej jeg tror ikke at instrument upload har noget at gøre med course backup fail ... jeg ville bare tage course backup før webupload i tilfælde af jeg lagde databasen ned med en dårlig karakter i instrumentet (som jeg erindrer er det faktisk sket for nogle år siden).  Det så dog heldigvis ud til at gå godt :)

Og ja, jeg ved godt at der stadig er qtype-algebra i kurset. Har ikke haft tid til at luge dte ud endnu og dit patch fik det jo heldigvis til at virke. Men er det derfor backup failer?

**Comment by willend** [comment]
Hejsa,

Hvis du tager et kig på de "templates" der ligger nu vil du se at tartu_swedness_20170914.mbz faktisk ligger der...

Sagen er at vi for nylig har kigget på at propagere "fejlmeddelelser" fra de underliggende kommandoer (såsom moosh der benyttes til at generere templates med) "op til" webserveren. Og pt. betyder det at der "kommer noget" på stderr fra moosh at webinterfacet går i en "fejl" tilstand.

Det betyder dog i praksis ikke at den udførte process ikke er gået godt... - Så du har fået din "template" (det er ikke en backup - der er ingen brugere eller brugerdata i... ;-) )

Så summa summarum: Der er "ikke noget galt" det ser bare sådan ud. Vi ændrer det ved lejlighed til en mindre "hård" måde at reagere på evt. stderr besked

**Comment by lindaudby** [comment]
Ok ang de fejlmeddelser der kommer fra moosh, kan godt se templaten (= backup uden brugere og brugerdata). Tænkte det var bedre at tage sådna een end intet når jeg nu har brugt dagevis på at rette forskellig opførsel i diverse quizzer til og lave nye quizzer.
Upload af instrument gik også fint, så nu er reflektometer aligment quizzen forhåbentlig snart klar.

**Comment by lindaudby** [comment]
mmmhhh ... og så alligevel ikke for simulation på instrumentet kører ikke
https://sim.e-neutrons.org/simrun/1911
Men muligvis hænger simulatoren i det hele taget lige nu? Prøvede også lige med et andet instrument
https://sim.e-neutrons.org/simrun/1913

**Comment by climbcat** [comment]
Godt at høre at tingene bliver klar! 

Har lige kigget lidt på mcstas-01 og elearn1. Det virker fint. Der er lavet en kø i simulatoren, så hvis mange sidder og kører simuleringer samtidigt kan den godt sidde og vente lidt i "init" tilstanden.

Ser ud som om nogle af dine studerende laver lektier eller noget ... 

drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:53 jaga15_SANSsimpleSpheres_20170914_145023
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:53 perizat_SimplePowderDiffractometer_20170914_141608
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:53 perizat_SimplePowderDiffractometer_20170914_141948
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:53 perizat_SimplePowderDiffractometer_20170914_142407
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:11 strandqvist_SimplePowderDiffractometer_20170914_141110
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:12 strandqvist_SimplePowderDiffractometer_20170914_141220
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:13 strandqvist_SimplePowderDiffractometer_20170914_141321
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:13 strandqvist_SimplePowderDiffractometer_20170914_141327
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:13 strandqvist_SimplePowderDiffractometer_20170914_141333
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:53 strandqvist_SimplePowderDiffractometer_20170914_141905
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:53 strandqvist_SimplePowderDiffractometer_20170914_141917
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:53 strandqvist_SimplePowderDiffractometer_20170914_142036
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:53 strandqvist_SimplePowderDiffractometer_20170914_142128
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:53 udby_reflectometer_alignment_20170914_144438
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:53 udby_reflectometer_alignment_20170914_144732
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:53 udby_reflectometer_alignment_20170914_145243
drwxr-sr-x 4 www-data www-data 4096 Sep 14 16:54 udby_SANSsimple_20170914_144756

**Comment by climbcat** [comment]
For the record: Moodle databasen er ikke i fare, medmindre man laver systemopdateringer eller moodleopdateringer. Simulatorens database er helt seperat. Prøv evt at uploade et "forkert" instrument, og se hvad der sker. Jeg vædder en bajer på at du ikke kan lægge noget som helst ned på den måde!

**Comment by lindaudby** [comment]
OK, jeg prøver at gøgle med mystiske karakterer når kurset er kørt. Så er det nok i det hele taget også på høje tid med en bajer, om det så bliver dig eller mig der giver ;)
