### ISSUE TITLE
Improvements to ldap_addusers.py script

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#16]
Code in https://github.com/McStasMcXtrace/McWeb/blob/master/ldifs/ldap_addusers.py
Based on csv file input ala

    firstname;lastname;username;email;description;password;course1
    John;Doe;johndoe;johndoe@dtu.dk;A user;kOde0rd.;10200

(Which works for upload in Moodle)

What works already is:
- Injection of users into LDAP

Further features required:
- Investigate if Moosh (http://www.somerandomthoughts.com/blog/2012/12/05/command-line-moodle-moosh/) can be used to create users automatically in Moodle
- Investigate if we need to create users in Mediawiki

**Comment by jaga-mcstas** [comment]
Comments on the above subtasks: 

Note:

- the "mcweb dynamic list of instr files" task removes the requirement to add users into the local Django database: Users are no longer associated with groups, which allows all users to view all instruments. What instrument group is currently visible/focused in the gui, is determined from the url.

**Comment by willend** [comment]
=> See newly added cronjob issue

**Comment by willend** [comment]
IMPORTANT: change , to ; ala above format, add headers etc..

**Comment by climbcat** [comment]
This is progressing nicely. Current issues: 

- implement filtering of user signup lines: generate "hold your horses for this user, username is already taken" csv to be edited and re-submitted by the admin (bare et forslag, lad os se på det)

**Comment by climbcat** [comment]
Addusers script is now tested to apply the password string added to the new_users.csv file by signupper. This works with LDAP also.

**Comment by climbcat** [comment]
The ldap_addusers.py script now appends successfully added user-lines to the file "added_YYYYMMDD.csv" (for example, added_20151221.csv), and removes those lines from the input file. Statuses is output the the terminal, but errors are only comprehensive in debug mode.

Users are expected to edit the input file and run the script again - until eventually, the input file is deleted and a message "all users have been added" is output by the script.

One issue remains, but is unrelated to the addusers scheme (LDAP related). 

So the task is done.

**Comment by willend** [comment]
Only transfer of info via mail / cron etc. is missing - make new issue on that, this one is DONE
