### ISSUE TITLE
how parameter descrption in header shows in web simulator

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#160]
In the instrument file I have
* %Parameters
* lambda_min:           [AA]   Minimum wavelength from source
* lambda_max:           [AA]   Maximum wavelength from source
* sampletranslation:    [m]    Sample translation (horizontal)
* slitwidth:            [m]    Width of slit pinholes                  
* slitheight:           [m]    Height of slit pinholes                 
* dist_source2slit:     [m]    Distance between source and first slit  
* dist_slit2slit:       [m]    Distance between slits                  
* dist_slit2sample:     [m]    Distance between second slit and sample 
* dist_sample2detector: [m]    Distance between sample and detector    
* sampletype:           [1]    Sample type: 0 none, 1 mirror, 2+ multilayer
* MR_Qc:                [AA^-1]   Critical Q-vector length of mirror sample
* sampleangle:          [deg]  Rotation angle of sample (theta)
* detectorangle:        [deg]  Rotation angle of detector window (2 theta)

But in the webinterface it shows like this
![screenshot from 2017-09-14 16-55-45](https://user-images.githubusercontent.com/15801156/30437674-748f6342-996f-11e7-8186-c06ab383578e.png)

I.e.teh description of the sampleangle and sampletranslation have not been shown in the same way as teh other parameters. What have I done wrong in the header file?

**Comment by climbcat** [comment]
Hi, this is not your fault - it is the parsing of documentation somewhere that is not outputting the proper bits of text.

**Comment by lindaudby** [comment]
Ok I think I have made a workaround in the input which works for sampletranslation now, but I cannot get the proper text printed for sampleangle . Tried this
* %Parameters
* lambda_min:           [AA]   Minimum wavelength from source
* lambda_max:           [AA]   Maximum wavelength from source
* sampletranslation:    [m]    Sample translation orthogonal to incoming beam
* slitwidth:            [m]    Width of slit pinholes                  
* slitheight:           [m]    Height of slit pinholes                 
* dist_source2slit:     [m]    Distance between source and first slit  
* dist_slit2slit:       [m]    Distance between slits                  
* dist_slit2sample:     [m]    Distance between second slit and sample 
* dist_sample2detector: [m]    Distance between sample and detector    
* sampletype:           [1]    Sample type: 0 none, 1 mirror, 2+ multilayer
* MR_Qc:                [AA^-1]   Critical Q-vector length of mirror sample
* sampleangle:          [deg]  Rotation angle of sample aka theta
* detectorangle:        [deg]  Rotation angle of detector window aka 2 theta
* beamstop:		[1]    If 0 the beamstop is out, if 1 it is in

**Comment by climbcat** [comment]
Ok, will fix after the firefox password bug.

**Comment by lindaudby** [comment]
Actually since I need a screendump of the interface to finish teh quiz and the students will do the quiz on Saturday this issue has higher priority ... will try and set the label correctly.

**Comment by willend** [comment]
My guess is that the parsing may have issues with the way the parameter list is constructed:
<pre>
DEFINE INSTRUMENT reflectometer(
  lambda_min           = 5.3,
  lambda_max           = 5.45,

  sampletranslation    = 0,   
  slitwidth            = 0.0006, 
  slitheight           = 0.08, 
       
  dist_slit2slit       = 3.2,   
   
  dist_sample2detector = 2,     
  sampletype           = 1,    
  
 
  MR_Qc                = 0.017,  // settings as sapphire
  sampleangle          = 0.2,  
  detectorangle        = 0 ,
  beamstop = 0 
)
</pre>
(There is for instance a comment within the list... - plus lots of empty lines etc.)

I will try to modify it to a more "classic" look and see if this helps

**Comment by willend** [comment]
Yup, that was it.

<img width="1060" alt="safariscreensnapz029" src="https://user-images.githubusercontent.com/8593355/30447077-38271adc-998b-11e7-85e0-c93cd35af2a9.png">

(Neither mcdoc nor this web interface is very forgiving... And what might look easier on the eye using an editor on the instr is not necessarily what the tools like... )

I belive we can close this one?

**Comment by lindaudby** [comment]
Yes, thanks!
