### ISSUE TITLE
scp file upload gives automatic rw - - rights only

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#163]
I've uploaded a large file 
scp Desktop/Tartu/Schweika_polarisation.pdf udby@e-neutrons.org:/srv/moodledata/repository/uploads/

Then I can normally add it as an activity in a course from within moodle. This however failed due to permission problems apparantly. Going back to check the server indeed settings were

-rw------- 1 udby     www-data   7847988 Sep 15 19:56 Schweika_polarisation.pdf

so I did 

chmod 644 Schweika_polarisation.pdf

And now I was able to add it form within moodle. But are think the 644 settigns used to be the standard when uploading via scp?

**Comment by willend** [comment]
Can surely be set via a umask setting or a sticky bit on the folder. Will look at that next week.

In the meantime I think the DAV upload gives mode 666, maybe try that? (URL is davs://sim.e-neutrons.org/dav/ i think ). I am however not sure what file size limits may exist

**Comment by lindaudby** [comment]
There is a finite amount of large files I need to transfer so can do the chmod manually (if that is OK ?) untill next week no problem.
The web-dav seems not to work for me anymore. 
Connet to server
davs://sim.e-neutrons.org/sim-dav
gives
Unhandled error message: Not a WebDAV enabled share

**Comment by willend** [comment]
Scp + chmod is OK.

As written above the dav URL is has been changed and gives access to both instr files and Moodle upload dir

**Comment by willend** [comment]
I have changed the default umask to 077, which seems to help here.

Please bear in mind however that if you use -p with your scp command, this will "preserve" file mode, meaning give user rwx only if this is what your file has locally.

**Comment by willend** [comment]
I believe this now works the way it should, closing
