### ISSUE TITLE
links to other intruments always referred to SANSsimple if user not logged in

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#167]
When a student is trying to solve a quiz by clicking  a link to a specific instrument e.g.
/sim/instrument/swedness/Ni_TAS
but is not at the same time logged into the simulator, they are asked to log in. 

But after logging in they are shown the default instrument https://sim.e-neutrons.org/instrument/intro-ns/SANSsimple , not the link they originally clicked. 
Can a specific instrument/link be ported through the login process?

**Comment by willend** [comment]
This has now been implemented on main and transported to the e-neutrons.org system.
