### ISSUE TITLE
course creation fails

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#171]
I tried to create a new course "Specialised Neutron Scattering" with shortname specialised-ns-master__20170928 from template intro-ns-withspecialised_master_20170928.mbz
But got this error message
![screenshot from 2017-09-28 11-30-36](https://user-images.githubusercontent.com/15801156/30959488-99ca899e-a440-11e7-9c6f-77393c9d5a7d.png)

The new course is to be tailored from specialised modules only and Viktor is about to build a simulation exercise quiz in it thus priority is high.

**Comment by lindaudby** [comment]
I think this is the problem:
ldap and signup dbs out of sync, could not proceed

Jakob can you please have a look?

**Comment by willend** [comment]
Tested to work with the latest patches, closing
