### ISSUE TITLE
Qt4->Qt5

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#173]
ESS DMSC colleagues were at the Qt World Summit summary earlier this week and report back that

"Nobody uses Qt 4.x anymore – we should upgrade to Qt 5.x sooner than later"

- The statement goes for SASview, but is just as relevant for McStas/McXtrace...

**Comment by climbcat** [comment]
I knew they were going to say that!

**Comment by willend** [comment]
This is in progress and should in fact have been placed at the McCode issues :-)
