### ISSUE TITLE
problem adding user fouquet

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#177]
I just bulk-added and enrolled the list of users for teh course on Monday hercules_20171004 
(I only got it now so could not do it before)
It seems that one user gave some problems

![screenshot from 2017-10-20 12-21-03](https://user-images.githubusercontent.com/15801156/31816641-62faa59a-b591-11e7-820b-fb56e2c2e116.png)

I cannot see him in the list of active users but I can seem him from inside moodle.
How can I figure out if he was sent an email and a pass?

**Comment by willend** [comment]
Peter Fouquet indeed already has an account "fouquet" - you can find him via the Moodle admin interface. (Listed as LDAP user and hence was originally sent a password)

I suggest you manually give him the needed credentials via Moodle. Wrt. password he may
a) Either use his original password
b) Change his password using https://www.e-neutrons.org/ssp/

Did all the other accounts get created?

**Comment by lindaudby** [comment]
Yes the other users got created and can be found on the "active users list" at https://sim.e-neutrons.org/manage/users
Only fouquet cannot be found there. Isn't that strange when he is listed as LDAP user?

I have added him to the course from within moodle and hope he can log i.
