### ISSUE TITLE
cannot add actvity or ressource in moodle

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#178]
![image](https://user-images.githubusercontent.com/15801156/31817096-f9ab8134-b592-11e7-934d-06c07b73edc2.png)
the "add ressource or activity" button/link has suddenly become inactive. (I see it but clicking does nothing)
This seems to be the case in all courses making me believe that it is a global moodle setting which somehow needs to be reset. 

I need to use the function to uoload material to the course today/tomorrow and on Monday the students will use it too in their exercises. So really hope that someone can try to reboot, restart worker or whatever it takes.

**Comment by lindaudby** [comment]
ok, seems to be a problem in Firefox (end very recently occurred only within last two days).
In chrome the link is active
![image](https://user-images.githubusercontent.com/15801156/31827501-36fbf076-b5b8-11e7-9dfb-1d99d918a9c6.png)

**Comment by willend** [comment]
Since we are dealing with web-technology, often updated and with slightly different behaviour across platforms, I hereby advice to always check with a different browser before reporting an issue.
