### ISSUE TITLE
mcdisplay-webgl, hanging instruments at e-neutrons.org

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#180]
Just found that a number of sim runs are stuck at e-neutrons.org:
<pre>
www-data 13583 13582  0 Oct23 ?        00:00:00 python /srv/mcweb/McCode/tools/Python/mcdisplay/webgl/mcdisplay.py ILL_H22_D1B.instr lambda=2.52 dlambda=0.03 DM=0 Powder=Na2Ca3Al2F14.laz RV=2.2 L1=0.25 L2=3 L3=1.5 TRAS_X=-0 TRAS_Z=0 TILT=0 THETA_M=22.11 R_pitch=0.42 R_ri=0.324 R_ro=0.419 R_h=0.09 R_ttmin=-130 R_ttmax=-2 R_present=1 verbose=1 Inc_Cryo=0.02 Trans_Cryo=0.85 Trans_Spl=0.2 Inc_Spl=0.05 m=2 mip=2 --nobrowse --dir=mcdisplay
www-data 14393 14392  0 Oct20 ?        00:00:00 python /srv/mcweb/McCode/tools/Python/mcdisplay/webgl/mcdisplay.py ILL_IN5.instr lambda=4.5 dlambda=0.05 speed=8500 ratio=0.5 housing=Fe.laz coh=Y3Fe5O12_YIG.laz inc=NULL thickness=0 height=0.025 radius=0.005 order=0 --nobrowse --dir=mcdisplay
www-data 14715 14714  0 Oct20 ?        00:00:00 python /srv/mcweb/McCode/tools/Python/mcdisplay/webgl/mcdisplay.py ILL_H22_VIVALDI.instr lambda=3 dlambda=2.2 crystal=YBaCuO.lau container=V.laz verbose=1 m=2 mip=2 --nobrowse --dir=mcdisplay
www-data 14878 14877  0 Oct23 ?        00:00:00 python /srv/mcweb/McCode/tools/Python/mcdisplay/webgl/mcdisplay.py ILL_H22_D1B.instr lambda=2.52 dlambda=0.03 DM=0 Powder=Na2Ca3Al2F14.laz RV=2.2 L1=0.25 L2=3 L3=1.5 TRAS_X=-0 TRAS_Z=0 TILT=0 THETA_M=22.11 R_pitch=0.42 R_ri=0.324 R_ro=0.419 R_h=0.09 R_ttmin=-130 R_ttmax=-2 R_present=1 verbose=1 Inc_Cryo=0.02 Trans_Cryo=0.85 Trans_Spl=0.2 Inc_Spl=0.05 m=2 mip=2 --nobrowse --dir=mcdisplay
www-data 15874 15873  0 Oct23 ?        00:00:00 python /srv/mcweb/McCode/tools/Python/mcdisplay/webgl/mcdisplay.py ILL_H22_D1B.instr lambda=2.52 dlambda=0.03 DM=0 Powder=Na2Ca3Al2F14.laz RV=2.2 L1=0.25 L2=3 L3=1.5 TRAS_X=-0 TRAS_Z=0 TILT=0 THETA_M=22.11 R_pitch=0.42 R_ri=0.324 R_ro=0.419 R_h=0.09 R_ttmin=-130 R_ttmax=-2 R_present=1 verbose=1 Inc_Cryo=0.02 Trans_Cryo=0.85 Trans_Spl=0.2 Inc_Spl=0.05 m=2 mip=2 --nobrowse --dir=mcdisplay
www-data 16034 16033  0 Oct24 ?        00:00:00 python /srv/mcweb/McCode/tools/Python/mcdisplay/webgl/mcdisplay.py ILL_H22_D1B.instr lambda=2.52 dlambda=0.03 DM=0 Powder=Na2Ca3Al2F14.laz RV=2.2 L1=0.25 L2=3 L3=1.5 TRAS_X=-0 TRAS_Z=0 TILT=0 THETA_M=22.11 R_pitch=0.42 R_ri=0.324 R_ro=0.419 R_h=0.09 R_ttmin=-130 R_ttmax=-2 R_present=1 verbose=1 Inc_Cryo=0.02 Trans_Cryo=0.85 Trans_Spl=0.2 Inc_Spl=0.05 m=2 mip=2 --nobrowse --dir=mcdisplay
www-data 16157 16156  0 Oct24 ?        00:00:00 python /srv/mcweb/McCode/tools/Python/mcdisplay/webgl/mcdisplay.py ILL_H22_D1B.instr lambda=2.52 dlambda=0.03 DM=0 Powder=Na2Ca3Al2F14.laz RV=2.2 L1=0.25 L2=3 L3=1.5 TRAS_X=-0 TRAS_Z=0 TILT=0 THETA_M=22.11 R_pitch=0.42 R_ri=0.324 R_ro=0.419 R_h=0.09 R_ttmin=-130 R_ttmax=-2 R_present=1 verbose=1 Inc_Cryo=0.02 Trans_Cryo=0.85 Trans_Spl=0.2 Inc_Spl=0.05 m=2 mip=2 --nobrowse --dir=mcdisplay
www-data 17210 17209  0 Oct24 ?        00:00:00 python /srv/mcweb/McCode/tools/Python/mcdisplay/webgl/mcdisplay.py ILL_D2B.instr lambda=1.594 DM=0 Powder=Na2Ca3Al2F14.laz RV=-1 L1=16.05 L2=2.645 L3=1.3 verbose=1 ALPHA1=18 ALPHA2=11 ALPHA3=5 ETA=12 THETA_M=67.5 TILT=0 SM=1 Dheight=0.3 coating=0 --nobrowse --dir=mcdisplay
www-data 17862 17861  0 Oct23 ?        00:00:00 python /srv/mcweb/McCode/tools/Python/mcdisplay/webgl/mcdisplay.py ILL_H22_D1B.instr lambda=2.52 dlambda=0.03 DM=0 Powder=Na2Ca3Al2F14.laz RV=2.2 L1=0.25 L2=3 L3=1.5 TRAS_X=-0 TRAS_Z=0 TILT=0 THETA_M=22.11 R_pitch=0.42 R_ri=0.324 R_ro=0.419 R_h=0.09 R_ttmin=-130 R_ttmax=-2 R_present=1 verbose=1 Inc_Cryo=0.02 Trans_Cryo=0.85 Trans_Spl=0.2 Inc_Spl=0.05 m=2 mip=2 --nobrowse --dir=mcdisplay
www-data 19184 19183  0 Oct23 ?        00:00:00 python /srv/mcweb/McCode/tools/Python/mcdisplay/webgl/mcdisplay.py ILL_H22_D1B.instr lambda=2.52 dlambda=0.03 DM=0 Powder=Na2Ca3Al2F14.laz RV=2.26 L1=0.25 L2=3 L3=1.5 TRAS_X=-0 TRAS_Z=0 TILT=0 THETA_M=22.11 R_pitch=0.6 R_ri=0.324 R_ro=0.419 R_h=0.49 R_ttmin=-130 R_ttmax=-2 R_present=0 verbose=1 Inc_Cryo=0.02 Trans_Cryo=0.85 Trans_Spl=0.2 Inc_Spl=0.05 m=2 mip=2 --nobrowse --dir=mcdisplay
www-data 19923 19922  0 Oct23 ?        00:00:00 python /srv/mcweb/McCode/tools/Python/mcdisplay/webgl/mcdisplay.py ILL_H22_D1B.instr lambda=2.52 dlambda=0.03 DM=0 Powder=Na2Ca3Al2F14.laz RV=2.26 L1=0.25 L2=3 L3=1.5 TRAS_X=-0 TRAS_Z=0 TILT=0 THETA_M=22.11 R_pitch=0.6 R_ri=0.324 R_ro=0.419 R_h=0.49 R_ttmin=-130 R_ttmax=-2 R_present=0 verbose=1 Inc_Cryo=0.02 Trans_Cryo=0.85 Trans_Spl=0.2 Inc_Spl=0.05 m=2 mip=2 --nobrowse --dir=mcdisplay
</pre>

We should debug these as the corresponding simulations will never end

**Comment by climbcat** [comment]
Ok, I'll have a look at these.

**Comment by climbcat** [comment]
I have tested the instruments by copying them locally and executing a current mcdisplay.

These two completed without problems:

ILL_H22_D1B
ILL_IN5.instr

These instruments had a compilation error in mcrun 2.4.1:

ILL_H22_VIVALDI.instr
ILL_D2B.instr

**Comment by climbcat** [comment]
The proposed solution is to introduce a reasonable timeout in the mcdisplay popen call to mcrun. Then at least this call can not hang indefinitely, which will fix the compilation error hang problem (and other similar potential problems).

The two instruments that did run locally are expected to work with a more recent version of mcdisplay.

**Comment by climbcat** [comment]
INFO: Using directory: "test3"
INFO: Recompiling: ./ILL_H22_VIVALDI.out
INFO: Regenerating c-file: ILL_H22_VIVALDI.c
Info:    'Al_window' is a contributed component.
Info:    Defining SPLIT from SamplePos=Arm() to END in instrument ILL_H22_VIVALDI
CFLAGS=
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp: In function ‘off_init’:
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:2798:23: warning: format ‘%i’ expects argument of type ‘int’, but argument 5 has type ‘long int’ [-Wformat=]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:2885:23: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp: In function ‘off_display’:
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:3096:24: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long int’ [-Wformat=]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:3096:24: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘long int’ [-Wformat=]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:3096:24: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 5 has type ‘long int’ [-Wformat=]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp: In function ‘off_init’:
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:2794:7: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:2881:7: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:2897:7: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
./ILL_H22_VIVALDI.c: In function ‘mcraytrace’:
./ILL_H22_VIVALDI.c:49484:6: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
./ILL_H22_VIVALDI.c: In function ‘mcinit’:
./ILL_H22_VIVALDI.c:23675:6: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
INFO: ===
Error: unrecognized parameter order (mcparseoptions)
Traceback (most recent call last):
  File "/usr/share/mcstas/2.4.1/bin/../tools/Python/mcrun/mcrun.py", line 372, in <module>
    main()
  File "/usr/share/mcstas/2.4.1/bin/../tools/Python/mcrun/mcrun.py", line 356, in main
    mcstas.run()
  File "/usr/share/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 208, in run
    return self.runMPI(args, pipe, override_mpi)
  File "/usr/share/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 227, in runMPI
    return Process(binpath).run(args, pipe=pipe)
  File "/usr/share/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 80, in run
    raise ProcessException(self.executable, args, retval)
mccode.ProcessException: Got exit status 1 from "./ILL_H22_VIVALDI.out --ncount 300.0 --dir test3 --format McStas --trace --no-output-files order=0 housing=Fe.laz lambda=4.5 inc=NULL speed=8500 coh=Y3Fe5O12_YIG.laz radius=0.005 thickness=0 ratio=0.5 height=0.025 dlambda=0.05"

**Comment by climbcat** [comment]
INFO: Using directory: "test4"
INFO: Recompiling: ./ILL_D2B.out
INFO: Regenerating c-file: ILL_D2B.c
Info:    Defining SPLIT from Monok=Monochromator_curved() to END in instrument ILL_D2B
Info:    Defining SPLIT from Arm_Sample=Arm() to END in instrument ILL_D2B
CFLAGS=
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp: In function ‘off_init’:
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:2798:23: warning: format ‘%i’ expects argument of type ‘int’, but argument 5 has type ‘long int’ [-Wformat=]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:2885:23: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp: In function ‘off_display’:
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:3096:24: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long int’ [-Wformat=]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:3096:24: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘long int’ [-Wformat=]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:3096:24: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 5 has type ‘long int’ [-Wformat=]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp: In function ‘off_init’:
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:2794:7: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:2881:7: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
/usr/share/mcstas/2.4.1/tools/Python/mcrun/../mccodelib/../../../monitors/Monitor_nD.comp:2897:7: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
INFO: ===
Error: unrecognized parameter ratio (mcparseoptions)
Traceback (most recent call last):
  File "/usr/share/mcstas/2.4.1/bin/../tools/Python/mcrun/mcrun.py", line 372, in <module>
    main()
  File "/usr/share/mcstas/2.4.1/bin/../tools/Python/mcrun/mcrun.py", line 356, in main
    mcstas.run()
  File "/usr/share/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 208, in run
    return self.runMPI(args, pipe, override_mpi)
  File "/usr/share/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 227, in runMPI
    return Process(binpath).run(args, pipe=pipe)
  File "/usr/share/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 80, in run
    raise ProcessException(self.executable, args, retval)
mccode.ProcessException: Got exit status 1 from "./ILL_D2B.out --ncount 300.0 --dir test4 --format McStas --trace --no-output-files ratio=0.5 coh=Y3Fe5O12_YIG.laz order=0 inc=NULL lambda=4.5 height=0.025 thickness=0 speed=8500 housing=Fe.laz radius=0.005 dlambda=0.05"

**Comment by willend** [comment]
Both of the above seems to stem from a set of "misunderstood" input parameters:
<pre>
Error: unrecognized parameter order (mcparseoptions)
</pre>
and
<pre>
Error: unrecognized parameter ratio (mcparseoptions)
</pre>

- Maybe a look at the instrument headers / parameter lists will show what exactly is going on?

**Comment by climbcat** [comment]
Right. Something strange happens when running

mcrun --info ILL_H22_VIVALDI.instr

as seen below. There are only five parameters in the instrument definition, but mcrun --info reports seven! The "m" parameter is documented in the header (outdated), while the word "mip" is not even in the instrument file.

****************************

loading user configuration from /home/jaga/.mcstas/2.4.1/mccode_config.json
INFO: No output directory specified (--dir)
INFO: Using directory: "ILL_H22_VIVALDI_20171101_125033"
INFO: Using existing binary: ./ILL_H22_VIVALDI.out
INFO: ===
info!
begin instrument: ILL_H22_VIVALDI
  Creator: McStas 2.4.1 - Jun. 26, 2017
  Source: ILL_H22_VIVALDI.instr
  Parameters:  lambda(double) dlambda(double) crystal(string) container(string) verbose(double) m(double) mip(double)
  Trace_enabled: yes
  Default_main: yes
  Embedded_runtime: yes
end instrument
begin simulation: .
  Format: McStas
  URL: http://www.mccode.org
  Creator: McStas 2.4.1 - Jun. 26, 2017
  Instrument: ILL_H22_VIVALDI.instr
  Ncount: 1000000
  Trace: no
  Gravitation: no
  Seed: 1509548186
  Directory: .
  Param: lambda=3
  Param: dlambda=2.2
  Param: crystal=YBaCuO.lau
  Param: container=V.laz
  Param: verbose=1
  Param: m=2
  Param: mip=2
end simulation

**Comment by climbcat** [comment]
Clearly the line 

%include "ILL_H22.instr"

Would have something to do with this.

**Comment by willend** [comment]
Right - understood!

The recipe to fix this for the future is to:
1) Make sure the instrument is compiled first
2) Ask for input parameters via ./binary.out ala
<pre>
./PSI_SANS_II.out --info
begin instrument: PSI_SANS_II
  Creator: McStas 2.4.1 - Jun. 26, 2017
  Source: PSI_SANS_II.instr
  Parameters:  lambda(double) SD(double) coll(double) para(double) parb(double) parc(double) bkg(double) scale(double)
  Trace_enabled: yes
  Default_main: yes
  Embedded_runtime: yes
end instrument
begin simulation: .
  Format: MCSTAS
  URL: http://www.mccode.org
  Creator: McStas 2.4.1 - Jun. 26, 2017
  Instrument: PSI_SANS_II.instr
  Ncount: 1000000
  Trace: no
  Gravitation: no
  Seed: 1509629508
  Directory: .
  Param: lambda=6
  Param: SD=6
  Param: coll=3
  Param: para=39.25
  Param: parb=1.3598
  Param: parc=3.8458
  Param: bkg=0.63806
  Param: scale=1.1488
end simulation
</pre>
- which will contain all supported input parameters, assembled via includes etc.

This of course leaves the issue of the instrument not itself "knowing" the significance, i.e. the documentation strings of all parameters "in one place". Either we live with that (leave empty on the web UI if files are assembled this way) or we find a way to look through headers of %included instr files...

**Comment by willend** [comment]
But for the problem at hand, mcdisplay should really only define / use input parameters resulting from ./binary.out --info

**Comment by climbcat** [comment]
ok! 

The other instrument runs fine on my system, even with python2 (python3 is formally the right version for mcdisplay-webgl) but it still hangs on the server.

**Comment by willend** [comment]
@ebknudsen and I just found that probably the old Perl tools use --help rather than --info, e.g. edit BNL_H8 to have this INSTRUMENT line:
<pre>
DEFINE INSTRUMENT BNL_H8(lambda,blha=5)
</pre>
Then the --help output includes
<pre>
Usage: ./BNL_H8.out [options] [parm=value ...]
Options are:
  -s SEED   --seed=SEED      Set random seed (must be != 0)
  -n COUNT  --ncount=COUNT   Set number of neutrons to simulate.
  -d DIR    --dir=DIR        Put all data files in directory DIR.
  -t        --trace          Enable trace of neutrons through instrument.
  -g        --gravitation    Enable gravitation for all trajectories.
  --no-output-files          Do not write any data files.
  -h        --help           Show this help message.
  -i        --info           Detailed instrument information.
  --format=FORMAT            Output data files using FORMAT=MCSTAS NEXUS

Instrument parameters are:
  lambda          (double)
  blha            (double) [default='5']
Known signals are: USR1 (status) USR2 (save) TERM (save and exit)
</pre>

**Comment by climbcat** [comment]
Great, it is easy to implement the same into the python tool.

**Comment by climbcat** [comment]
test result:

ILL_IN5.instr hangs even with python3. It runs fine locally. Perhaps we could look at this together whenever next time is?

**Comment by willend** [comment]
Yes, let's do that. If I remember correctly, e-neutrons.org (still) runs mcstas-2.3 (plus extra stuff in the form of mcdisplay-webgl), maybe this is the cause of some mal-functionality...

**Comment by willend** [comment]
I am now upgrading to 2.4.1 - let's see if that gives us any milage

**Comment by willend** [comment]
VIVALDI runs: http://sim.e-neutrons.org/static/data/mcstas_ILL_H22_VIVALDI_20171102_084553/browse.html

H22_D1B runs: http://sim.e-neutrons.org/static/data/mcstas_ILL_H22_D1B_20171102_084657/browse.html

IN5 runs: http://sim.e-neutrons.org/static/data/mcstas_ILL_IN5_20171102_084752/browse.html

D2B runs: http://sim.e-neutrons.org/static/data/mcstas_ILL_D2B_20171102_084842/browse.html

**Comment by willend** [comment]
(Local mcdisplay-webgl is from the repos rather than the one from 2.4.1)

I think we should still
a) refactor for use of --help when picking up input parameters
b) implement a (2 minute? / settings file) timeout for the mcdisplay runs

**Comment by climbcat** [comment]
Ok!:)

**Comment by willend** [comment]
Only a small part remaining - now put in

**Comment by willend** [comment]
https://github.com/McStasMcXtrace/McWeb/issues/186
