### ISSUE TITLE
MXRUN vs MCRUN usage in collect_instr non-functional

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McWeb#184]
The change 4789e9cc343dd0191b7c7eabe9ce198e2e706d73 seems to invalidate the collect_instr command, at least on my system. Removing this change the command started working again.

**Comment by willend** [comment]
After a short discussion, the code in https://github.com/McStasMcXtrace/McWeb/commit/4789e9cc343dd0191b7c7eabe9ce198e2e706d73 should be re-introduced, but "display_name" used instead of "instr_file".

**Comment by willend** [comment]
Implicit in https://github.com/McStasMcXtrace/McWeb/issues/153, closing
