### ISSUE TITLE
Persistent storage maximum size reached

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#185]
![screenshot from 2017-11-15 11-43-49](https://user-images.githubusercontent.com/15801156/32832044-81a7dd82-c9fa-11e7-8d0b-cac808c5ee7e.png)

When logging in this morning this error message occurs. 
When closing it reopens on every action in moodle making it impossible to do view or alter content.

**Comment by willend** [comment]
I can not reproduce this in my browser. As the error message mentions some java script, I suggest you try with a different browser / empty your caches etc.

![safariscreensnapz054](https://user-images.githubusercontent.com/8593355/32833838-9312bdb6-ca00-11e7-9e68-9ce606c7dcb0.png)

**Comment by lindaudby** [comment]
OK, seems to be a firefox issue. Sorry didn't realise it may be a browser issue thought it had something to do with disk space (storage)

**Comment by willend** [comment]
It has to do with "local storage" in the browser - and as far as I know maybe privacy settings somehow

**Comment by lindaudby** [comment]
OK, thanks for explaining :)
