### ISSUE TITLE
Timeout for mcdisplay runs in in simrunner (job-control)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#186]
Implement a (2 minute? / settings file) timeout for the mcdisplay runs 

(to avoid blocking the rest of the simulator / server)

**Comment by climbcat** [comment]
The popen call should probably be put into a local thread and polled periodically. It is already in a thread, which may provide an opportunity, otherwise a third "polling-thread" may be introduced.

**Comment by willend** [comment]
Closing as #223 mentions this
