### ISSUE TITLE
Platform: Wiki page on Moodle + nginx requires further work

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#19]
The instructions in this page:
https://github.com/McStasMcXtrace/McCode/wiki/Setting-up-moodle-with-LDAP-authentication
are not sufficient for a succesful install on my current vmware Debian 8 machine - needs a look at...

**Comment by jaga-mcstas** [comment]
Looks like the docs simply does not say anything about LDAP :-D regardless of debian version. Or are you experiencing specific debian-8 related issues?

**Comment by willend** [comment]
True :-) I have started fixing this, adding in a few more comments. 
The main problem was being allowed in at /moodle/index.php in the first place - seems using the mcweb_default nginx conf gave me some milage... ;-)
At this point my moodle is running, but configuration against the LDAP is not functional yet - will look at mcstas-01 to see if anything is obviously different.. - and then Document something (tm) ;-)

**Comment by willend** [comment]
Is becoming duplicate of (now closed) issue pointing to new instructions at https://github.com/McStasMcXtrace/McWeb/wiki. Closing
