### ISSUE TITLE
New release of qalgebra plugin

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#190]
I got anotification that there was a new release of qalgebra. Has this been installed?
If the update solves the problem we have had with this plugin it would be great :)

**Comment by lindaudby** [comment]
![image](https://user-images.githubusercontent.com/15801156/35275986-eb0db8be-0041-11e8-8993-18dacc636a7e.png)

**Comment by willend** [comment]
I think it has been installed now (unfortunately this seems not fully automated) see https://www.e-neutrons.org/moodle/admin/index.php?cache=1 that now looks like this:

<img width="982" alt="safariscreensnapz071" src="https://user-images.githubusercontent.com/8593355/35276135-9e3c1a48-0042-11e8-9b8d-b94314ebe3cc.png">

**Comment by lindaudby** [comment]
OK thanks :)

**Comment by willend** [comment]
- And about "solving the problem we had with this plugin", it at least solves the problem of that plugin not being officially supported in "new" moodle releases.

**Comment by lindaudby** [comment]
Yes! That is good news indeed! :)

**Comment by willend** [comment]
- On the downside, all of the qtype regex things are now not officially supported in Moodle 3.4... (But seem to run still...)

**Comment by lindaudby** [comment]
Hmm it seems that somehow the install of qtype algebra was not complete?

Screenshot from 2018-01-24 13-30-29

I think we use regex very little so far so it is not a big issue if we should avoid it in future content

**Comment by lindaudby** [comment]
![image](https://user-images.githubusercontent.com/15801156/35332413-25cb51a4-010b-11e8-96f6-3ac97c3afcca.png)

**Comment by willend** [comment]
You are very welcome to pres "Install this update" whenever you come across a notification like that - this is exactly what I would do myself... 

It is on the other hand also important to press the "cron" link afterwards - which may include some final steps. https://www.e-neutrons.org/moodle/admin/cron.php

**Comment by willend** [comment]
Aehm done i guess
