### ISSUE TITLE
moodle update prompt

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#194]
Er det her en af den slags prompter man skal trykke "continue" til?

**Comment by lindaudby** [comment]
![image](https://user-images.githubusercontent.com/15801156/35866342-3bd26248-0b57-11e8-90d5-36252a82a066.png)

**Comment by willend** [comment]
Der plejer så at komme noget "upgrade database?" bagefter - også bare fortsætte der.

**Comment by lindaudby** [comment]
Screenshot from 2018-02-06 16-05-37

**Comment by lindaudby** [comment]
![image](https://user-images.githubusercontent.com/15801156/35866511-ac2d9738-0b57-11e8-8e05-f30d4c784ea0.png)

**Comment by willend** [comment]
Jep, Continue på trods af den lille advarsel der

**Comment by lindaudby** [comment]
![image](https://user-images.githubusercontent.com/15801156/35866621-fc25a7da-0b57-11e8-84a7-52a936b8e09e.png)

**Comment by lindaudby** [comment]
OK, har pgså klikket videre til cron.php scriptet der kører nu

**Comment by willend** [comment]
Og så gerne klikke på det der cron.php til slut

**Comment by willend** [comment]
Fino.
