### ISSUE TITLE
mcweb-ng, status page add missing links etc.

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#20]
Priority: 1000

**Comment by climbcat** [comment]
I have updated the simrunner backend to comply with the mcsimulator standard (see f22060a)

**Comment by climbcat** [comment]
The following was added to the status page: links to stdout, stderr, simrun.tar.gz. Fixed images. Log scale viewing now works.

**Comment by climbcat** [comment]
BUT: folder stuff is a mess. models.SimRun needs a rework of its database fields related to files and folders.

**Comment by climbcat** [comment]
ok this task is done
