### ISSUE TITLE
Link not working in some browsers

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#202]
On page https://www.e-neutrons.org/?page_id=280 (from front pahge go to quiz taster)
![image](https://user-images.githubusercontent.com/15801156/37210925-9fd9105a-23aa-11e8-9704-b7752905ba45.png)

On Tommy Windows 10 the link "Quiz taster" does not work. It works on my Ubuntu Crome

**Comment by willend** [comment]
What does "does not work" mean? 

Does it not show?
Does it look weird?
Is there an error message?

**Comment by lindaudby** [comment]
No error message

**Comment by climbcat** [comment]
This should be easy to fix by going into the page in wordpress and fixing and testing the link. Do you have an account on wordpress?

**Comment by lindaudby** [comment]
Yes, but the problem is that it works fine in my Ubuntu browsrs crome and firefox and I don't have a Windows 10 to test.

**Comment by willend** [comment]
I had a look - it looks like some other link on "earlier" on the page is was not terminated properly. I've hacked in a </a> before the link in question and things seems to work... 

Please confirm/ close accordingly

**Comment by willend** [comment]
Since I heard nothing further I will assume this was OK
