### ISSUE TITLE
mcweb-ng, config page add tooltips, units, default values etc.

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#21]
Priority: 1000

**Comment by climbcat** [comment]
@willend what is a good way to extract the tooltip and unit for params from instrument files? ATM. I am just using the stuff from mcgui-py to parse 'mcrun --info' output (e.g. no tooltip or unit)

**Comment by willend** [comment]
mcdoc is probably the easiest way - try mcdoc -t instr

(And now I remember - this is likely why we ran two mcdocs in the past - one for generating .html and the other one to grab these defaults etc.)

**Comment by climbcat** [comment]
I guess this task is done :-D
