### ISSUE TITLE
Clock on e-neutrons server (moodle)

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#210]
Since we would like to time e-leanring content in courses to e.g.  f2f lectures in hand-on courses it is important that the internal clock is correct ta e-neutrons, specifically moodle. 
Currently it seems to be ~1 hour late according to real time.

**Comment by willend** [comment]
If this is the case it must be a Moodle setting... From here it looks like mcstas-01 is 10 minutes after current time, see this screenshot:

![screen shot 2018-09-05 at 15 57 06](https://user-images.githubusercontent.com/8593355/45098142-a92c6c80-b124-11e8-8f83-033d57e624f9.png)

**Comment by willend** [comment]
Moodle / content, @udby if this is still relevant could you have a look in Moodle settings?

**Comment by lindaudby** [comment]
I ust tested by a quiz timing here 
https://www.e-neutrons.org/moodle/mod/quiz/view.php?id=5059 
It looks to be working as it should now, closing.
