### ISSUE TITLE
mcweb-ng, css styling etc.

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#22]
Priority: 900

**Comment by climbcat** [comment]
I've updated simrunner backend to comply with mcsimulator "status" page standards (see f22060a).

**Comment by climbcat** [comment]
This is more or less done, I suppose. I have nothing in the pipeline and no further ideas for now.

**Comment by willend** [comment]
Cool, will test it all later! :-)

Technical University of Denmark


Department of Physics
Neutrons and X-rays for Materials Physics
Fysikvej

Building 307<x-apple-data-detectors://1/0>

DK-2800 Kongens Lyngby<x-apple-data-detectors://1/0>

Direct +45 2125 4612<tel:+45%202125%204612>

Mobil +45 2125 4612<tel:+45%202125%204612>
Fax +45 4593 2399<tel:+45%204593%202399>



pkwi@fysik.dtu.dk<mailto:pkwi@fysik.dtu.dk>

Den 10/12/2015 kl. 18.26 skrev "Jakob Garde" <notifications@github.com<mailto:notifications@github.com>>:


This is more or less done, I suppose. I have nothing in the pipeline and no further ideas for now.
