### ISSUE TITLE
Broken link to SANS sim project in Moodle?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#221]
In intro-ns on the page https://www.e-neutrons.org/moodle/course/view.php?id=2&section=3, the link Simulation project: A small angle neutron scattering experiment (https://www.e-neutrons.org/moodle/mod/url/view.php?id=4285) leads nowhere relevant on the wiki it seems

**Comment by willend** [comment]
@udby bringing this to your attention

**Comment by lindaudby** [comment]
I have tried to change/fix the incorrect link but it seems moodle now does not recognise the path as an URL. I only inserted "SANS-2" in the link so the beginning of the path /wiki/.... is unchanged

![Selection_140](https://user-images.githubusercontent.com/15801156/60382198-20d6d980-9a60-11e9-9370-4b60482a4d3c.png)

the full link is
https://www.e-neutrons.org/wiki/index.php?title=Simulation_project_SANS-2:A_small_angle_neutron_scattering_instrument

**Comment by willend** [comment]
OK, could be the original-original link was included as https://... something that was then stripped off of the http etc. hostname later by direct editing of the database.

I guess there is no way around using a full link then.

**Comment by lindaudby** [comment]
OK, let us hope that it is a singular problem.
I have set the full path in the link now, closing

**Comment by lindaudby** [comment]
There seems to be a general problem so will post another ticket.
