### ISSUE TITLE
1. Idealised HEIMDAL diffractometer - for magnetism case

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#227]
Ingredients:

* Source_simple (emits all wavelengths at same time, i.e. t=0)
* PowderN with  https://github.com/McStasMcXtrace/SINE2020WP3_instruments/blob/master/HEIMDAL/CoFe2O4.txt
* NPI_tof_dhkl_detector.comp (taken from https://github.com/McStasMcXtrace/McCode/blob/master/mcstas-comps/examples/ESS_BEER_MCPL.instr - in a non-modulation oriented setting)

**Comment by willend** [comment]
The instr is now in the repo. The standard pyqtgraph plotter crashes if one applies log on the 2 last monitors.

**Comment by willend** [comment]
Reflection lists for [CoFe2O4](https://github.com/McStasMcXtrace/SINE2020WP3_instruments/blob/master/HEIMDAL/CoFe2O4_109044.txt) and [CoFe](https://github.com/McStasMcXtrace/SINE2020WP3_instruments/blob/master/HEIMDAL/CoFe_56273.txt) are now in the repo

**Comment by climbcat** [comment]
https://github.com/McStasMcXtrace/SINE2020WP3_instruments/blob/master/HEIMDAL/ESS_HEIMDAL.instr

The above instrument has been updated to something that displays the desired peaks in the dhkl detector.

**Comment by willend** [comment]
DONE
