### ISSUE TITLE
2. Temperature-effect in PowderN(1)  - for magnetism case

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#228]
"stretch" lattice with temperature - linear scale

**Comment by willend** [comment]
![Screenshot 2019-06-06 at 13 51 57](https://user-images.githubusercontent.com/8593355/59031532-3f342580-8864-11e9-956d-8e563ffd7228.png)

**Comment by willend** [comment]
Idea: 
In a local PowderN (renamed?) version, implement a Temperature-input and "stretch" all powder lines accordingly around line 585 (for loop)

**Comment by climbcat** [comment]
In PowderN.comp, I believe it should be around line 685.

**Comment by willend** [comment]
Status: Magnetic peak present, overall normalisation and strecth of lattice with temperature is missing
