### ISSUE TITLE
3. Temperature-effect in PowderN(2)  - for magnetism case

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#229]
Using a WHEN, makes temperature-dependent rise of a new compound (single-reflection)

**Comment by willend** [comment]
![Screenshot 2019-06-06 at 13 51 57](https://user-images.githubusercontent.com/8593355/59031561-4ce9ab00-8864-11e9-892b-7d207d773fef.png)
- expressed as 2 in the figure

**Comment by willend** [comment]
This one is simple, given temperature T and Curie temperature Tc,
```
COMPONENT Magnet = PowderN(...)
AT (SOMEWHERE,0,0)
EXTEND %{
if (T<Tc && T>=0) {
     p *= (Tc-T)/(T);
}
  else
    ABSORB;
%}
```
Overall intensity-scaling between 1 and 2 is done by a WHEN (assign %-age to one vs the other)

**Comment by willend** [comment]
If we need further broadening of peak 2, a way would be to add a gaussian smearing on the outgoing direction, in a the above EXTEND 
```
EXTEND %{
       double d0,d1,d2,nrm;
       nrm=sqrt(vx*vx+vy*vy+vz*vz);
       randvec_target_circle(&d0, &d1, &d2, NULL, vx, vy, vz, sin(dir_smear*DEG2RAD));
	NORM(d0,d1,d2);
    vx=d0*nrm;
    vy=d1*nrm;
    vz=d2*nrm;   
      }
    }
    
%}
```

**Comment by climbcat** [comment]
Tweaking  the "cif" file to contain only one crystal-clear magnetic peak at around d=4.8 does not seem to be as simple as removing crystal brag condition lines. 

![image](https://user-images.githubusercontent.com/11196009/59441156-6eb0d800-8df8-11e9-8b73-5f1a292eca2b.png)

**Comment by willend** [comment]
Status: Low-d peak was caused by incoherent scattering, removed inrepo.
Magnetic peak present, overall normalisation wrt. the other peaks and stretch of lattice with temperature is missing
