### ISSUE TITLE
4. Model 2 of the instrument, introduce reduction / reaction time

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#230]
WHEN between multiple (4-5?) PowderN's as function of reaction time to produce

![Screenshot 2019-06-06 at 14 13 44](https://user-images.githubusercontent.com/8593355/59031934-5889a180-8865-11e9-9f7b-438b4cd7c620.png)

- 3

**Comment by climbcat** [comment]
sample_1 selected by samplerate = 1:
![image](https://user-images.githubusercontent.com/11196009/59599052-e7b47600-90fd-11e9-8ea9-229b2950334f.png)

sample_2 selected by samplerate = 0:
![image](https://user-images.githubusercontent.com/11196009/59599104-0581db00-90fe-11e9-980c-e495a3cd9d89.png)

**Comment by willend** [comment]
Clear how this should be done @climbcat says
