### ISSUE TITLE
Configurable mcplot in mcsimrunner

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#24]
@climbcat  The mcsimrunner_ng runworker should have a configurable mcplot

<pre> cmd = 'mcplot-gnuplot-py -s %s' % f </pre>

- i.e. cmd should be read from the settings file so that a non-gnuplot mcplot may be used

Most of the other mcplot variants have a syntax like this one
mcplot -png monitorfile

**Comment by climbcat** [comment]
what could other mcplot command strings look like? (f is a .dat file btw.)

**Comment by willend** [comment]
Oldschool PGPLOT:
<pre>cmd = 'mcplot -png %s' % f</pre>
python-matplotlib:
<pre>cmd = 'mcplot-matplotlib-py -f %s' % f</pre>

There may be more that differ slightly from this, but these are the most important ones

**Comment by willend** [comment]
So how about just allowing to define mcplotstring in the settings.py  including a %s and use

<pre> cmd = mcplotstring % f?

**Comment by climbcat** [comment]
Ok, hm... one way is to put three lines in settings.py: 

MCPLOT_CMD = 'mcplot -png'
# MCPLOT_CMD = 'mcplot-matplotlib-py -f'
# MCPLOT_CMD = ''mcplot-gnuplot-py -s'

Then out-comment the line we want to use, and replace the line in runworker.py with this: 

cmd = '%s %s' % (MCPLOT_CMD, f)

**Comment by climbcat** [comment]
damn.,,thats ugly

**Comment by willend** [comment]
Hehe :+1: :) Let's see tomorrow?

**Comment by climbcat** [comment]
sure :-P

**Comment by willend** [comment]
Not to pretty, but now done
