### ISSUE TITLE
Output directories need either username or session id included for uniqueness

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#25]
A folder like mcstas_PSI_DMC_20151203_185419 may accidentally get created from two sessions / users simultaneously... For uniqueness we should probably include a username or session id in that dirname

**Comment by climbcat** [comment]
The data folders are currently username_instrdisplayname_datetime. Group is not part of the name (should it be?). Inside the dirname, a folder called mcstas is created which contains the mcstas output files. It is very easy to change - we just change the return value of the function __str__() in simrunner.models.SimRun

**Comment by climbcat** [comment]
The "data_folder" property on simrunner.models.SimRun becomes this, written by runworker:

<pre>"%s_%s_%s" % (self.owner_username, self.instr_displayname, str(self.created.strftime("%Y%m%d_%H%M%S")))</pre>
