### ISSUE TITLE
ng: static files serving in production

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McWeb#26]
We will need a bit of fiddling with some django and nginx settings to be able to view images and serve files in production.

**Comment by willend** [comment]
Likely to be configured as an 'ordinary' webserver-indexed location in NGINX, e.g.

<pre>
	location /static/ {
		alias /srv/mcweb/McWeb/mcsimrunner_ng/static/;
		autoindex on;
		allow all;
	}
</pre>
