### ISSUE TITLE
ng: runworker executes wrml viewer UI

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McWeb#27]

**Comment by willend** [comment]
Ah, sure. Not so difficult to fix. The mcstas_config.perl (in /usr/share/mcstas/x.y/tools/Perl/) of the system should be configured with e.g.

BROWSER='echo'

instead of the default xdg-open
(or put a tweaked mcstas_config.perl in the .mcstas/ folder of the webserver user)

**Comment by willend** [comment]
See README.md to unconfigure whitedune
