### ISSUE TITLE
ng: click on images to get plot, second click to get .dat file

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McWeb#29]

**Comment by climbcat** [comment]
I am planning to implement this by generating static html for each simrun: It should work like this: 

- the live-rendered **simrun/\<group\>/\<simrun\>** is rendered by simrunner.views.simrun. Right now it returns the template status.html, which is configured to have a refresh-rate of 4 secs. When the simrun is done, the same template is rendered, complete with plots, and set to a refresh-rate of 3600 secs. (:+1:) This will change such that instead of rendering the same template, the view function generates a static page, saves it on disk and redirects to that page.

- **static/data/<\simrun__data_folder\>/browse.html** is a static url pointing at the browse.html file that is located in the data folder, and was generated by the view as described above. It links to other html pages within the same data directory.

- **static/data/<\simrun__data_folder\>/mcstas/PSD_mon.html** (and sweep_monitor.html (see below)): This is a simple html file with an image (src="PSD_mon.png") inside an \<a\> tag with href="PSD_mon.dat".

- for the scan sweep case, e.g. scansteps \> 1, we render a browse.html file from a different template. All in all we will have the following html templates, from which django will generate the static browse pages:
        - **browse.html** (equivalent with the mcwww "status" page)
        - **browse_scansweep.html** (also the status page, but for scan sweeps (monitors are links beneath a sweep overview)
        - **sweep_monitor.html** (presents a single monitor as it develops through a scan sweep - arrived at by clicking on a monitor link in browse_scansweep.html)
        - **monitor.html** (a single monitor image which can be clicked to get the .dat file of any name, used by single-step and scan sweep simulations)

The degree of linking between lin/log can be discussed, but we might as well include it everywhere (and implement a js to catch keypresses of 'l').

This will allow us to serve all simulation results as static content, which has a number of advantages: It is lightning fast, it can be served without login credentials, it can be linked, shared and viewed by anyone at any time the server is up.

We also save a lot of python-processing time by generating the pages once and for all. These are completely deterministic once the simulation run is done, so why have a dynamic django function generate them over and over to serve this static content., every time someone clicks on an image or views a status page or clicks on a static, pre-generated image.

Finally, we limit the complexity of the django python code by incapsulating the logics for browsing the status pages in a "generate_status_pages" function. Not need to have multiple urls and functions in views for this. Although it can be done, I think we would become slow, buggy and confused.

A drawback might be that we will have a lot of html pages in every data folder - and one for every .png file (except layout.png). However, I don't think this is such a big drawback. First of all the files are rather small compared to the simulation output (each html maybe a tenth of a .png monitor image), and second, these html images are not included in the .tar.gz download file, which is generated by runworker prior to html browse files generation.

NOTE: We should NOT generate the html's from runworker, but rather directly from the views. The time-consuming part is saving each file on the disk, not generating the data in django (which is comparable to calling a normal django view function).

**Comment by climbcat** [comment]
something like this ... 
<pre>
document.onkeypress = function(e) {
  if(e.keyCode == 90) {
    // z pressed
  }
}
</pre>

**Comment by willend** [comment]
- Or just a simple <a href=""> on the image linking into the right place in /static?

BTW fine by me to have the view generate flat html pages

**Comment by climbcat** [comment]
Ok cool, it's gonna be an awesome site that way

**Comment by climbcat** [comment]
this task is done
