### ISSUE TITLE
Changing old simulaitons/running a second (different) simulation

### ISSUE THREAD

**Issue by morbidslug** [McStasMcXtrace/McWeb#3]
Upon running simulation the params variable is set any change of choice of simulation uses the same params, throwing a KeyError on  the attempt to run the new simulation (saving the job). The same issue exists on loading an old simulation from the list.

- The reference for the job remains the same upon hitting 'Run this config' button.

**Comment by willend** [comment]
For the time being, we will not fix this - may come with enhancements on Mark's branch
