### ISSUE TITLE
The instrument page shows a duplicated set of parameters

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#31]
Have a look here
<img width="1552" alt="safariscreensnapz036" src="https://cloud.githubusercontent.com/assets/8593355/11600558/ba5a79e0-9acd-11e5-8dfc-52bad86d1ada.png">

**Comment by climbcat** [comment]
hmmm :+1: thanks

**Comment by climbcat** [comment]
fixed, due to a bug in collect_instr. The page correctly showed db contents
