### ISSUE TITLE
Error handling in status view

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#33]
Give label 
Simulation: Error and provide access to stdout and stderr in the frontend in case the worker experiences an error from mcrun or mcplot (maybe mcdisplay)

**Comment by climbcat** [comment]
done, a fail page is written if the simulation fails.

However, we should generate a static fail page in case of a fail, and that isn't done at the momen

**Comment by willend** [comment]
My opinion is that this can be considered DONE for now
