### ISSUE TITLE
Separate 'am i logged in ?' page for top-right corner of Wordpress front page

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#34]

**Comment by willend** [comment]
If logged in displays 'Logged in as <username> [logout]'
If not logged in displays the standard username / passwd [login] from

(Consider separate css styling so that it can match the Wordpress look)

**Comment by willend** [comment]
(consider including the hidden 'iframe' for the  moodle page)

**Comment by climbcat** [comment]
this page has been implemented at /loginstatus

**Comment by willend** [comment]
Yup, looks good. We should probably add the 'hack' hidden iFrame for simultaneous moodle login to login-slim. Maybe with settings.py setting for enabling/disabling

**Comment by willend** [comment]
Integration in the wp site missing - otherwise DONE
