### ISSUE TITLE
Platform: mcstas-01 'demo' deployment

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#35]

**Comment by willend** [comment]
DONE wrt the simrunner_ng,

**Comment by willend** [comment]
Try 
1) enabling the LDAP auth on the new simrunner
2) locating the new simrunner in an url like  hostname.domainname/folder

**Comment by climbcat** [comment]
Isn't all of the above already done?

**Comment by willend** [comment]
That depends... The mediawiki and moodle systems are not 100% configured yet. :-)

**Comment by willend** [comment]
Apart from fine polishing, I consider this DONE
