### ISSUE TITLE
Ensure to start multiple worker processes - otherwise only one runs at a time...

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#37]

**Comment by climbcat** [comment]
Oooooh thread safety! No problem, we just need a few critical sections

**Comment by willend** [comment]
This part actually worked fine in the older setups (including the flask one in Munich) simply by starting multiple manage.py runworker .

(And seems to be the same here by trial and error - do you really think it is necessary to do clever thread-handling here?)

Technical University of Denmark


Department of Physics
Neutrons and X-rays for Materials Physics
Fysikvej

Building 307<x-apple-data-detectors://1/0>

DK-2800 Kongens Lyngby<x-apple-data-detectors://1/0>

Direct +45 2125 4612<tel:+45%202125%204612>

Mobil +45 2125 4612<tel:+45%202125%204612>
Fax +45 4593 2399<tel:+45%204593%202399>



pkwi@fysik.dtu.dk<mailto:pkwi@fysik.dtu.dk>

Den 10/12/2015 kl. 00.08 skrev "Jakob Garde" <notifications@github.com<mailto:notifications@github.com>>:


Oooooh thread safety! No problem, we just need a few critical sections

**Comment by climbcat** [comment]
we don't have actualy critical sections, but a much smaller likelyhood that a clash will happen. This is because the multithreading happens from an external process

**Comment by willend** [comment]
Seems to work OK now, closing.
