### ISSUE TITLE
Admin site organisation

### ISSUE THREAD

**Issue by morbidslug** [McStasMcXtrace/McWeb#4]
- Would be nice to display the params dictionaries in a nice way instead of spitting it out as a string.
- Preferable to redesign admin site so that: Users can be batch added to groups
                                                                     Simulations/Jobs/SimRun operations are in one place
                                                                     and refer to one another.
Overall Admin
--------------------
The delete simulation option should delete/move simulation files on the server out of their group folder.
Should include: searching/filtering with status
                          searching by user name
                          ordering by something, maybe user/created posn on stack (if change job ordering)
- Functionality: Job Promotion/Demotion
                        Job Deletion
                        Kill Run (server side for clean up)
                        Removing Job from stack (server side clean up)
                        Pause (server side clean up and rebuild)

**Comment by willend** [comment]
For the time being we are keeping the internal structure of McWeb as is, marking as wontfix + closing
