### ISSUE TITLE
Platform: documentation rewrite

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McWeb#42]

**Comment by willend** [comment]
Two strategies:
1) Create a set of wiki pages with main entries
simrunner_ng
uploader
moodle
mediawiki
LDAP
etc.
With tips on installation and configuration of the various things

2) Make a "clean" deployed setup, stripped from passwords etc - and generate an OS image with all software included

**Comment by willend** [comment]
Is being populated at https://github.com/McStasMcXtrace/McWeb/wiki

**Comment by willend** [comment]
Skeleton DONE, closing to clear TODO item
