### ISSUE TITLE
Platform: ldap scripts improvements

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McWeb#55]
- ldap db entry uniqueness changed from full name to username
- ldap_initdb.py should detect dn automatically
- create a script ldap_removeusers.py that can remove specific users from the ldap db

**Comment by climbcat** [comment]
pt. 1 has been implemented.

WARNING: this may cause wiki/moodle auth to fail for users added using the new script, but we can quickly fix this. Also, we should wipe the existing ldap to avoid being confused later.

**Comment by climbcat** [comment]
pt. 2 has been implemented and email is now supported and added to ldap

**Comment by willend** [comment]
removeusers is also implemented, DONE, closing
