### ISSUE TITLE
Simrunner: Add (hidden) iFrame for Moodle login

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#59]

**Comment by climbcat** [comment]
a hidden iframe and submit target has been added to the login_slim.html template. Moodle login part is untested. Note: the moodle iframe now has display:none, so it is invisible on the page. moodle behavior in another browser window must be observed as a test.

**Comment by climbcat** [comment]
I think we completed this yesterday :-)

**Comment by willend** [comment]
Yup, this is done. https://github.com/McStasMcXtrace/McWeb/issues/71 is a pointer to a possibly easy way of getting mediawiki on board also...
