### ISSUE TITLE
mcweb does not easily allow a prefix URL e.g. /mcweb/

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#6]
Having had a look on mcstas-01, edits to these files seemed not enough:

On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   mcwww/settings.py
	modified:   mcwww/urls.py
	modified:   mcwww/views.py
	modified:   nginx/mcweb_nginx.conf
	modified:   templates/mcwww/login.html

Full list of edits below:
[edits.txt](https://github.com/McStasMcXtrace/McWeb/files/24279/edits.txt)

**Comment by willend** [comment]
It might be that the issues had to do with not restarting the uwsgi service - should be checked...

**Comment by jaga-mcstas** [comment]
Changing all of the above allows us to login, but not simulate. Actually, it might just be this: http://stackoverflow.com/questions/10313475/moving-django-apps-into-subfolder-and-url-py-error

**Comment by morbidslug** [comment]
I get the feeling that it's more likely that the view templates, redirects or renders are now incorrect rather than a directory issue.

**Comment by jaga-mcstas** [comment]
I changed five files to include /simulator/ as a prefix to all url's and it didn't work. Therefore I changed it back and started looking for a more direct and cleaner solution.

**Comment by jaga-mcstas** [comment]
Now I've done this: 

rewrite ^/moodle/(.*\.php)(/)(.*)$ /moodle/$1?file=/$3 last;

It is not what we want exactly, but it does redirect from /simulator to the default location of mcsimulator.

**Comment by willend** [comment]
Hi there, seems it only works if there is a trailing slash '/' in the URL (i.e. http://mcstas-01.risoe.dk/simulator will not work (simple to fix of course)

**Comment by willend** [comment]
Hi again, what is worse:

It seems the rewrite hack now prevents the login form from working...

**Comment by morbidslug** [comment]
The trailing slash is a django thing, I have fixed it in urls.py by adding ?'s after the last '/' in the address. We could also fix in settings.py with:
```APPEND_SLASH=True```
but I like the urls approach better.

**Comment by jaga-mcstas** [comment]
The trailing slash as a django thing is unrelated to the nginx rewrite. It also should not affect login at all - I tested the app after and it worked. It must be something else - will test properly when the server is up and running =)

**Comment by willend** [comment]
The server is back up! :+1:

**Comment by willend** [comment]
May be easier to do with "mcweb-ng" reimplementation, otherwise we have workarounds...
