### ISSUE TITLE
Platform: Cronjobs and scripts

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#60]
* Cronjob: Daily batch of "subscription requests" to "the admin" - sends back instructions for adding users
* Script: When adding users, these should be informed via email about their credentials etc.
* Cronjob: Auto-compile of newly added instruments / images. Make time-stamped backup of django db

**Comment by willend** [comment]
One more item here: 
* cli/cron.php maintenance script for moodle should be run on a daily basis

**Comment by climbcat** [comment]
a script now exist for moving new_signups.csv to new_20160107 (e.g.) and sending an email to the admin (hardcoded in the script)

another script exists for notifying all added users

However, the cronjobs aren't wor

**Comment by climbcat** [comment]
The update_instr cronjob is also not working yet. I modified /var/www to be root:www-data, and have w rights on group. This was required for crontab to edit a hidden file in that folder. The jobs should be run as www-data. However, it didn't work quite yet.

**Comment by climbcat** [comment]
Cronjobs have been activated and tested. 

This is the first instrument that was added to the simulator by use of the uploader and a cronjob: http://sim.e-neutrons.org/instrument-menu/group1/templateSANS_Mantid - i.e. without any access to the server file system

**Comment by willend** [comment]
Nice! :-) Who gets the admin mails?

**Comment by climbcat** [comment]
The person who is hardcoded into the script :-)

**Comment by climbcat** [comment]
btw, there is no admin email for the update_instr.sh script run, other than the cron one with script output

**Comment by willend** [comment]
Looks good! I suggest that we (after release) might

1) Suppress output if the status is "sim folder checksum has not changed, exiting."
2) Send the output to someone if actions are indeed performed...

**Comment by willend** [comment]
I further added a call to the moodle cron.php script in the crontab.

I think we can close...

**Comment by willend** [comment]
I have done a test also - works nicely indeed. :+1: :-)

http://sim.e-neutrons.org/instrument/test/ILL_BRISP (with overview graphics) was uploaded this way, simulation output is available here: 
http://sim.e-neutrons.org/static/data/pwillendrup_ILL_BRISP_20160112_124143/browse.html

One comment about the uploader though: 
The selector automatically pops back to "datafiles", so uploading one more file easily makes that the second file goes to the datafiles folder... Maybe the list should include <PLEASE SELECT SOMETHING> or similar - being the default - so that people less easily accidentally upload to the wrong location...

**Comment by climbcat** [comment]
Nice, that's a nice instrument too :-)

Alright, will do something to improve that.
