### ISSUE TITLE
Signupper: Place added_ files in folder accessible by moodle

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#69]
Moodle has access to /srv/moodledata/repository/uploads - meaning that there is no need for copying the csv files around!!

**Comment by climbcat** [comment]
That's a big usability advantage!:-)

**Comment by climbcat** [comment]
This functionality has been added to the script ldap_addusers.py as the last step, if the new_ file is deleted, a copy of the added_  file is created in moodledata. This happens via the script cptomoodledata.sh

**Comment by willend** [comment]
Works! Marking as DONE.
(But please check that www-data:www-data has ownership of the file in the  moodledata place)

**Comment by climbcat** [comment]
www-data should have ownership, because, the ldap_addusers.py and new_signups.csv both have ownership and group as www-data. In order to change this, they have to be run with sudo, or as www-data. At least it looked like the file added_YEARDATE always turns out to be owned by www-data. 

Hmmm...
