### ISSUE TITLE
Auto-compilation of new/updated instr files

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#8]
Write a cron job to run every 30 minutes with the tasks:
- Check if anything was modified in the sim/ folder
- If so, take a backup of the django DB
- Run / compile instruments
- Check if that went OK and update DB, otherwise fallback to backup

**Comment by jaga-mcstas** [comment]
The cron job should also syncdb in case any folders has been added/removed. (This functionality needs to be tested pretty thorougly)

**Comment by jaga-mcstas** [comment]
Script for cron use now created. The checksum mechanism can only see changes to actual files. Further issues are; 
- our django commands can not handle removal of instruments
- instrument names have to be unique across groups, even though the code in command populate_db does not reflect this
- cron job supposed to execute from project root

It's calling update_simulations.sh in case it detects a change, which calls mcrun to do the compilation. This means that only the required compilations are carried out, and this is handled by mcrun. Nice and simple.

**Comment by jaga-mcstas** [comment]
The pkwillend cronjob file has been moved to scripts/ and modified to target update_instr.sh. This script will do a checksum check and compile.

Missing: 
- backup of db, check and possible restore.
- activation and test of the actual job

**Comment by willend** [comment]
Done, closing
