### ISSUE TITLE
Admintool: New Django app to web-enable the tasks of enrolling new users

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#81]
- Should be password protected (single, non-LDAP password)
- Should feature
  - Possible upload of CSV file (or via the existing upload app) with addition to new_DATE.csv (passwords should probably be generated on the fly
  - Possibility to sanity-check / edit the new_DATE.csv file
  - Run the ldap_addusers.py
  - Deep-link to the "upload users" part of Moodle
  - Run the notify_users.py

**Comment by willend** [comment]
A related edit to ldap_addusers would be to call e.g. pwgen if the password field of the CSV file is empty

**Comment by climbcat** [comment]
Alright, cool, what about we apply mooshe and thus avoid any "limbo" users? Then the addition is one, single step. Then possibly the admin could go into moodle afterwards to adjust settings for specific users if needed.

**Comment by willend** [comment]
Agreed, we should indeed check if this is possible.

Peter

On 21 Jan 2016, at 15:38 , Jakob Garde <notifications@github.com<mailto:notifications@github.com>> wrote:


Alright, cool, what about we apply mooshe and thus avoid any "limbo" users? Then the addition is one, single step. Then possibly the admin could go into moodle afterwards to adjust settings for specific users if needed.

**Comment by willend** [comment]
I just installed moosh to the production system - looks really great! I will try to patch the ldap_useradd script to enable user creation in moodle + enrollment:

<pre>
www-data@mcstas-01:/home/srv/mcweb/moodle$ moosh  user-create --help
*** user-create ***
OPTIONS:
	-h, --help
		help information

	-a, --auth=<value>
		authentication plugin, e.g. ldap

	-p, --password=<value>
		password (NONE for a blank password)

	-e, --email=<value>
		email address

	-c, --city=<value>
		city

	-C, --country=<value>
		country

	-f, --firstname=<value>
		first name

	-l, --lastname=<value>
		last name

	-i, --idnumber=<value>
		idnumber

	-d, --digest=<value>
		mail digest type as int (0=No digest, 1=Complete, 2=Subjects)


ARGUMENTS:
	username ...

www-data@mcstas-01:/home/srv/mcweb/moodle$ moosh course-enrolbyname --help    
*** course-enrolbyname ***
OPTIONS:
	-h, --help
		help information

	-i, --id=<value>
		use this user id instead of user name

	-r, --role=<value>
		role short name

	-f, --firstname=<value>
		users firstname

	-l, --lastname=<value>
		users lastname

	-c, --cshortname=<value>
		course shortname


ARGUMENTS:
	courseid username ...
</pre>

**Comment by willend** [comment]
Here are the necessary commands

<pre>
sudo -u www-data moosh user-create --auth=ldap --email=john@doe.com --password=NONE johndoe
sudo -u www-data moosh course-enrol -s lib johndoe
sudo -u www-data moosh course-enrol -s musr johndoe
...
</pre>

**Comment by willend** [comment]
If <pre>--password=NONE</pre> is not used, it seems moodle tries to set the password with use of ldap - which fails.

**Comment by climbcat** [comment]
The admin tool is underway. Here are the current tasks: 

- copy ldap functionality from /useradmin into mcsimrunner_ng/signupper/ldaputils
- implement mooshe backend functionality in utils.py or a new file
- apply this backend in django views
- implement userdetail_au.html functionality (edit single Signup instance)
- implement upload of csv to assign signups in that way (must be moodle-compatible csv for now)
- apply simplified cron email-to-admin to go to <oursite>/login_au.html and submit signups 
- test signup pipeline and make adjustments
- depricate current useradmin pipeline

**Comment by climbcat** [comment]
You can currently go to /login_au.html (must be django superuser account) to test functionality. This is safe because there is no backend. First run the command      

    $ python manage.py migrate

To sync the django db to the new Signup model now included in signupper.
