### ISSUE TITLE
Urgent: Redirect or add information on old pages, linking to the e-neutrons.org website

### ISSUE THREAD

**Issue by PJRay** [McStasMcXtrace/McWeb#82]
As an example, the wiki page https://vntwiki.mcstas.org/index.php?title=Main_Page is still up and running, looking like it always has. We need to tell users that we are moved to the new domain, so they see the most updated version of the site. I'm guessing it's the same problem on moodle and the livesim pages?

Would the ideal solution simply be redirects?

**Comment by willend** [comment]
I have now "parked" the vnt wiki/moodle/simulator at DTU - see e.g.

https://vntmoodle.mcstas.org

Currently without a redirect.
