### ISSUE TITLE
fail when space in scan interval on sim

### ISSUE THREAD

**Issue by juliehougaard** [McStasMcXtrace/McWeb#88]
Hi, 

When there is a space in the interval like: 6, 7 the simulator fails to run the scan.

Perhaps this could be fixed with something that removes all spaces in the input string.

**Comment by climbcat** [comment]
Hi, it has been fixed (1b9bc20).

**Comment by willend** [comment]
@climbcat for some reason I can not get this onto the simulator at e-neutrons.org by a git pull, could you have a look?

**Comment by climbcat** [comment]
Tested again, it works.
